module.exports = {
  add: ["book", "new", "add", "template", "repo-template"],
  airplane: ["airplane", "plane", "sharp", "airplane-sharp"],
  alarm: ["alarm", "clock", "sharp", "time", "alarm-sharp"],
  albums: ["albums", "boxes", "sharp", "slides", "square", "albums-sharp"],
  alert: [
    "!",
    "alert",
    "attention",
    "exclamation",
    "notice",
    "sharp",
    "warning",
    "alert-sharp"
  ],
  analytics: [
    "analytics",
    "data",
    "metrics",
    "sharp",
    "track",
    "analytics-sharp"
  ],
  aperture: [
    "aperture",
    "dark",
    "images",
    "levels",
    "light",
    "settings",
    "sharp",
    "aperture-sharp"
  ],
  apps: ["applications", "apps", "sharp", "apps-sharp"],
  archive: ["compress", "archive", "file-zip"],
  at: ["at", "ping", "mention"],
  attach: ["anchor", "attach", "chain", "href", "link", "sharp", "link-sharp"],
  backspace: ["backspace", "sharp", "backspace-sharp"],
  bandage: ["bandage", "sharp", "bandage-sharp"],
  barbell: [
    "barbell",
    "exercise",
    "lifting",
    "sharp",
    "weight",
    "barbell-sharp"
  ],
  barcode: ["barcode", "camera", "reader", "sharp", "barcode-sharp"],
  baseball: ["baseball", "sharp", "baseball-sharp"],
  basket: ["basket", "sharp", "basket-sharp"],
  basketball: ["team", "game", "basketball", "jersey"],
  beaker: ["beaker", "flask", "mixture", "potion", "sharp", "beaker-sharp"],
  bed: ["bed", "hotel", "sharp", "sleep", "bed-sharp"],
  beer: ["beer", "drink", "eat", "food", "sharp", "beer-sharp"],
  bicycle: ["bicycle", "bike", "exercise", "sharp", "bicycle-sharp"],
  bluetooth: ["bluetooth", "cloud", "connection", "sharp", "bluetooth-sharp"],
  boat: ["boat", "sharp", "boat-sharp"],
  body: ["body", "sharp", "body-sharp"],
  bonfire: ["bonfire", "heat", "hot", "sharp", "bonfire-sharp"],
  book: ["book", "new", "template", "repo-template-private"],
  bookmark: ["unsaved", "bookmark"],
  bookmarks: ["bookmarks", "favorite", "sharp", "bookmarks-sharp"],
  briefcase: ["briefcase", "folder", "organize", "suitcase", "business"],
  browsers: ["browsers", "sharp", "square", "browsers-sharp"],
  brush: ["brush", "sharp", "brush-sharp"],
  bug: ["bug", "develop", "error", "hacker", "program", "sharp", "bug-sharp"],
  build: ["build", "sharp", "build-sharp"],
  bulb: ["bulb", "sharp", "bulb-sharp"],
  bus: ["bus", "sharp", "bus-sharp"],
  business: ["briefcase", "folder", "organize", "suitcase", "business"],
  cafe: ["cafe", "coffee", "cup", "sharp", "cafe-sharp"],
  calculator: ["arithmetic", "calculator", "math", "sharp", "calculator-sharp"],
  calendar: ["calendar", "date", "month", "sharp", "week", "calendar-sharp"],
  call: ["call", "sharp", "telephone", "call-sharp"],
  camera: ["camera", "film", "movie", "sharp", "videocam", "videocam-sharp"],
  car: ["car", "sharp", "sport", "car-sport-sharp"],
  card: [
    "$",
    "card",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "price",
    "sharp",
    "shopping",
    "card-sharp"
  ],
  cart: ["cart", "sharp", "cart-sharp"],
  cash: ["cash", "money", "sharp", "wallet", "wallet-sharp"],
  cellular: ["cellular", "sharp", "cellular-sharp"],
  chatbox: ["chatbox", "sharp", "chatbox-sharp"],
  chatbubble: ["chatbubble", "sharp", "chatbubble-sharp"],
  chatbubbles: ["chatbubbles", "sharp", "talk", "chatbubbles-sharp"],
  checkbox: ["checkbox", "sharp", "checkbox-sharp"],
  checkmark: ["checkmark", "sharp", "shield", "shield-checkmark-sharp"],
  clipboard: ["copy", "paste", "save", "capture", "clipboard", "clippy"],
  close: ["remove", "close", "delete", "x"],
  cloud: [
    "cloud",
    "rainy",
    "sharp",
    "water",
    "weather",
    "whether",
    "rainy-sharp"
  ],
  cloudy: [
    "cloudy",
    "lightning",
    "overcast",
    "rain",
    "sharp",
    "sky",
    "storm",
    "thunderstorm",
    "weather",
    "whether",
    "thunderstorm-sharp"
  ],
  code: ["terminal", "code", "ops", "shell"],
  cog: ["cog", "gear", "options", "settings", "sharp", "cog-sharp"],
  compass: [
    "compass",
    "directions",
    "location",
    "navigation",
    "sharp",
    "compass-sharp"
  ],
  construct: ["construct", "sharp", "construct-sharp"],
  contract: ["contract", "sharp", "contract-sharp"],
  contrast: [
    "contrast",
    "dark",
    "images",
    "levels",
    "light",
    "settings",
    "sharp",
    "contrast-sharp"
  ],
  copy: ["book", "journal", "copy", "repo-forked"],
  create: ["create", "edit", "sharp", "create-sharp"],
  crop: ["crop", "sharp", "crop-sharp"],
  cube: ["box", "container", "cube", "sharp", "square", "cube-sharp"],
  cut: ["cut", "sharp", "cut-sharp"],
  desktop: ["desktop", "sharp", "desktop-sharp"],
  disc: ["cd", "disc", "sharp", "vinyl", "disc-sharp"],
  document: ["document", "sharp", "text", "document-text-sharp"],
  documents: ["documents", "sharp", "documents-sharp"],
  download: ["clone", "download", "desktop-download"],
  duplicate: ["branch", "git", "fork", "duplicate", "git-branch"],
  ear: ["ear", "sharp", "ear-sharp"],
  earth: ["globe", "internet", "world", "earth", "planet"],
  easel: ["easel", "sharp", "easel-sharp"],
  egg: ["baby", "bird", "birth", "egg", "sharp", "twitter", "egg-sharp"],
  ellipse: ["circle", "ellipse", "sharp", "ellipse-sharp"],
  enter: ["door", "arrow", "direction", "enter", "log in", "sign-in"],
  exit: ["fullscreen", "expand", "exit", "screen-normal"],
  expand: ["fullscreen", "expand", "exit", "screen-normal"],
  eye: ["exposed", "eye", "look", "see", "sharp", "view", "eye-sharp"],
  eyedrop: ["eyedrop", "sharp", "eyedrop-sharp"],
  female: [
    "dudette",
    "female",
    "girl",
    "lady",
    "sharp",
    "woman",
    "woman-sharp"
  ],
  film: ["camera", "film", "movie", "sharp", "videocam", "videocam-sharp"],
  filter: ["filter", "sharp", "filter-sharp"],
  fitness: ["fitness", "sharp", "fitness-sharp"],
  flag: ["favorite", "flag", "marker", "sharp", "flag-sharp"],
  flame: ["fire", "flame", "heat", "hot", "sharp", "flame-sharp"],
  flash: ["flash", "lightning", "sharp", "weather", "whether", "flash-sharp"],
  flashlight: ["flashlight", "sharp", "flashlight-sharp"],
  flask: ["bubbles", "flask", "mixture", "potion", "sharp", "flask-sharp"],
  flower: ["flower", "rose", "sharp", "rose-sharp"],
  folder: ["folder", "subfolder", "link", "alias", "file-symlink-directory"],
  football: ["football", "sharp", "soccer", "football-sharp"],
  funnel: ["funnel", "sharp", "sort", "funnel-sharp"],
  gift: ["gift", "package", "present", "skill", "craft", "freebie"],
  glasses: [
    "glasses",
    "look",
    "reading",
    "see",
    "sharp",
    "steve",
    "glasses-sharp"
  ],
  globe: [
    "globe",
    "home",
    "nature",
    "planet",
    "sharp",
    "space",
    "world",
    "planet-sharp"
  ],
  golf: ["golf", "sharp", "golf-sharp"],
  grid: ["grid", "menu", "sharp", "grid-sharp"],
  hammer: ["hammer", "options", "settings", "sharp", "tools", "hammer-sharp"],
  happy: [
    "fun",
    "good",
    "happy",
    "like",
    "sharp",
    "smile",
    "yes",
    "happy-sharp"
  ],
  headset: ["headset", "sharp", "headset-sharp"],
  heart: ["heart", "love", "sharp", "heart-sharp"],
  help: [
    "?",
    "circle",
    "help",
    "information",
    "question",
    "sharp",
    "help-sharp"
  ],
  home: [
    "globe",
    "home",
    "nature",
    "planet",
    "sharp",
    "space",
    "world",
    "planet-sharp"
  ],
  hourglass: ["hourglass", "sharp", "time", "hourglass-sharp"],
  image: ["image", "video", "audio", "file-media"],
  images: ["images", "photo", "sharp", "images-sharp"],
  infinite: ["unlimited", "infinite", "infinity"],
  information: [
    "?",
    "circle",
    "help",
    "information",
    "question",
    "sharp",
    "help-sharp"
  ],
  journal: ["book", "journal", "repository", "put", "repo-push"],
  key: ["access", "key", "sharp", "key-sharp"],
  keypad: ["keypad", "sharp", "type", "keypad-sharp"],
  language: ["language", "sharp", "language-sharp"],
  laptop: ["apple", "laptop", "macbook", "osx", "sharp", "laptop-sharp"],
  layers: ["layers", "sharp", "layers-sharp"],
  leaf: ["green", "leaf", "nature", "plant", "recycle", "sharp", "leaf-sharp"],
  library: ["library", "sharp", "library-sharp"],
  link: ["link", "alias", "file-symlink-file"],
  list: ["list", "sharp", "list-sharp"],
  locate: ["gps", "locate", "maps", "navigate", "sharp", "locate-sharp"],
  location: ["gps", "location", "navigation", "pin", "sharp", "pin-sharp"],
  magnet: ["attraction", "magnet", "sharp", "sticky", "magnet-sharp"],
  mail: ["mail", "todo", "new", "messages", "inbox"],
  male: ["boy", "dude", "guy", "male", "man", "sharp", "man-sharp"],
  man: ["boy", "dude", "guy", "male", "man", "sharp", "man-sharp"],
  map: ["gps", "location", "map", "navigate", "pin", "sharp", "navigate-sharp"],
  medal: ["medal", "sharp", "medal-sharp"],
  medical: ["medical", "sharp", "medical-sharp"],
  medkit: [
    "case",
    "disease",
    "firstaid",
    "health",
    "medkit",
    "sharp",
    "sick",
    "medkit-sharp"
  ],
  megaphone: ["megaphone", "bullhorn", "loud", "shout", "broadcast"],
  menu: ["hamburger", "menu", "dropdown", "three-bars"],
  mic: ["mic", "noise", "sharp", "sound", "speaker", "talk", "mic-sharp"],
  moon: ["dark", "moon", "night", "sharp", "sky", "moon-sharp"],
  move: ["move", "sharp", "move-sharp"],
  navigate: [
    "gps",
    "location",
    "map",
    "navigate",
    "pin",
    "sharp",
    "navigate-sharp"
  ],
  newspaper: ["newspaper", "sharp", "newspaper-sharp"],
  notifications: ["notifications", "sharp", "notifications-sharp"],
  nuclear: ["danger", "hazard", "nuclear", "sharp", "warning", "nuclear-sharp"],
  nutrition: ["nutrition", "sharp", "nutrition-sharp"],
  open: ["email", "open", "mail-read"],
  options: ["hammer", "options", "settings", "sharp", "tools", "hammer-sharp"],
  pause: ["break", "freeze", "hold", "music", "pause", "sharp", "pause-sharp"],
  paw: ["paw", "sharp", "paw-sharp"],
  pencil: ["pencil", "sharp", "pencil-sharp"],
  people: ["people", "group", "team", "organization"],
  person: ["person", "remove", "sharp", "person-remove-sharp"],
  pin: ["gps", "location", "navigation", "pin", "sharp", "pin-sharp"],
  pint: ["pint", "sharp", "pint-sharp"],
  pizza: ["drink", "eat", "food", "pizza", "sharp", "pizza-sharp"],
  planet: [
    "globe",
    "home",
    "nature",
    "planet",
    "sharp",
    "space",
    "world",
    "planet-sharp"
  ],
  play: ["loud", "volume", "audio", "sound", "play", "unmute"],
  podium: [
    "award",
    "compete",
    "competition",
    "lose",
    "podium",
    "sharp",
    "win",
    "podium-sharp"
  ],
  power: ["off", "on", "power", "sharp", "power-sharp"],
  pricetag: [
    "$",
    "commerce",
    "items",
    "money",
    "pricetag",
    "sharp",
    "shopping",
    "pricetag-sharp"
  ],
  pricetags: [
    "$",
    "commerce",
    "items",
    "money",
    "pricetags",
    "sharp",
    "shopping",
    "pricetags-sharp"
  ],
  print: ["print", "sharp", "print-sharp"],
  pulse: ["hot", "live", "pulse", "rate", "graph", "trend", "line", "activity"],
  push: ["push", "sharp", "push-sharp"],
  radio: ["music", "radio", "sharp", "radio-sharp"],
  rainy: [
    "cloud",
    "rainy",
    "sharp",
    "water",
    "weather",
    "whether",
    "rainy-sharp"
  ],
  reader: ["reader", "sharp", "reader-sharp"],
  receipt: ["receipt", "sharp", "receipt-sharp"],
  recording: [
    "film",
    "recording",
    "sharp",
    "tape",
    "voicemail",
    "recording-sharp"
  ],
  refresh: ["sync", "cycle", "refresh", "loop"],
  reload: ["reload", "sharp", "reload-sharp"],
  remove: ["remove", "close", "delete", "x"],
  repeat: ["repeat", "sharp", "repeat-sharp"],
  resize: ["resize", "sharp", "resize-sharp"],
  restaurant: ["eat", "restaurant", "sharp", "restaurant-sharp"],
  ribbon: ["ribbon", "sharp", "ribbon-sharp"],
  rocket: ["rocket", "sharp", "rocket-sharp"],
  rose: ["flower", "rose", "sharp", "rose-sharp"],
  sad: ["bad", "cry", "no", "sad", "sharp", "sad-sharp"],
  save: ["electricity", "lightning", "props", "like", "star", "save", "zap"],
  scan: ["scan", "sharp", "scan-sharp"],
  school: ["school", "sharp", "school-sharp"],
  search: ["glass", "magnifying", "search", "sharp", "search-sharp"],
  send: ["email", "paper", "send", "sharp", "send-sharp"],
  server: ["server", "sharp", "server-sharp"],
  settings: ["hammer", "options", "settings", "sharp", "tools", "hammer-sharp"],
  shapes: ["shapes", "sharp", "shapes-sharp"],
  share: ["share", "sharp", "social", "share-social-sharp"],
  shield: ["security", "shield", "protection", "fail", "shield-x"],
  shirt: ["sharp", "shirt", "shirt-sharp"],
  shuffle: ["random", "sharp", "shuffle", "shuffle-sharp"],
  skull: ["sharp", "skull", "skull-sharp"],
  snow: ["cold", "sharp", "snow", "snow-sharp"],
  speedometer: [
    "drive",
    "level",
    "sharp",
    "speed",
    "speedometer",
    "speedometer-sharp"
  ],
  square: ["sharp", "square", "square-sharp"],
  star: ["electricity", "lightning", "props", "like", "star", "save", "zap"],
  stop: ["stop", "block", "spam", "report"],
  stopwatch: ["sharp", "stopwatch", "time", "stopwatch-sharp"],
  subway: ["sharp", "subway", "subway-sharp"],
  sunny: [
    "light",
    "sharp",
    "sky",
    "sunny",
    "weather",
    "whether",
    "sunny-sharp"
  ],
  sync: ["sharp", "sync", "sync-sharp"],
  tennisball: ["sharp", "tennisball", "tennisball-sharp"],
  terminal: ["sharp", "terminal", "terminal-sharp"],
  text: ["font", "size", "text", "text-size"],
  thermometer: [
    "cold",
    "heat",
    "hot",
    "mercury",
    "sharp",
    "temperature",
    "thermometer",
    "thermometer-sharp"
  ],
  thunderstorm: [
    "cloudy",
    "lightning",
    "overcast",
    "rain",
    "sharp",
    "sky",
    "storm",
    "thunderstorm",
    "weather",
    "whether",
    "thunderstorm-sharp"
  ],
  time: ["time", "past", "revert", "back", "history"],
  timer: ["clock", "sharp", "timer", "timer-sharp"],
  today: ["sharp", "today", "today-sharp"],
  toggle: ["sharp", "switch", "toggle", "toggle-sharp"],
  train: ["sharp", "train", "train-sharp"],
  transgender: ["sharp", "transgender", "transgender-sharp"],
  trash: ["close", "delete", "remove", "sharp", "trash", "trash-sharp"],
  triangle: ["triangle", "arrow", "chevron-right"],
  trophy: [
    "award",
    "compete",
    "competition",
    "lose",
    "sharp",
    "trophy",
    "win",
    "trophy-sharp"
  ],
  tv: ["sharp", "television", "tv", "tv-sharp"],
  umbrella: [
    "dry",
    "rain",
    "sharp",
    "shelter",
    "umbrella",
    "wet",
    "umbrella-sharp"
  ],
  videocam: ["camera", "film", "movie", "sharp", "videocam", "videocam-sharp"],
  walk: ["sharp", "walk", "walk-sharp"],
  wallet: ["cash", "money", "sharp", "wallet", "wallet-sharp"],
  warning: ["sharp", "warning", "warning-sharp"],
  watch: ["watch", "view", "media", "stream", "device-camera-video"],
  water: ["sharp", "water", "water-sharp"],
  wifi: ["bars", "connection", "internet", "sharp", "wifi", "wifi-sharp"],
  wine: ["glass", "sharp", "wine", "wine-sharp"],
  woman: ["dudette", "female", "girl", "lady", "sharp", "woman", "woman-sharp"],
  bell: ["notification"],
  bold: ["markdown", "bold", "text"],
  broadcast: ["broadcast", "radio-tower"],
  browser: ["window", "web"],
  check: [
    "security",
    "shield",
    "protection",
    "check",
    "success",
    "shield-check"
  ],
  checklist: ["todo", "tasks"],
  clippy: ["copy", "paste", "save", "capture", "clipboard"],
  clock: [
    "clock",
    "hour",
    "minute",
    "second",
    "sharp",
    "time",
    "watch",
    "time-sharp"
  ],
  comment: ["speak", "bubble"],
  dash: ["deleted", "subtracted", "dash", "diff-removed"],
  dashboard: ["speed", "dial"],
  database: ["disks", "data"],
  dependent: ["dependency", "dependent", "file"],
  diff: ["diff", "changes", "request", "request-changes"],
  ellipsis: ["ellipsis", "sharp", "vertical", "ellipsis-vertical-sharp"],
  file: ["dependency", "dependent", "file"],
  fold: ["unfold", "hide", "collapse"],
  gear: ["cog", "gear", "options", "settings", "sharp", "cog-sharp"],
  gist: ["gist", "secret", "private", "gist-secret"],
  grabber: ["mover", "drap", "drop", "sort"],
  graph: ["hot", "live", "pulse", "rate", "graph", "trend", "line", "activity"],
  history: ["history", "commits", "versions"],
  hubot: ["robot", "bot"],
  inbox: ["mail", "todo", "new", "messages"],
  infinity: ["unlimited", "infinite"],
  info: ["help"],
  italic: ["font", "italic", "style"],
  jersey: ["team", "game", "basketball"],
  keyboard: ["type", "keys", "write", "shortcuts"],
  law: ["legal", "bill"],
  lock: ["protect", "shield", "lock", "shield-lock"],
  markdown: ["markdown", "bold", "text"],
  mention: ["at", "ping"],
  milestone: ["marker"],
  mirror: ["reflect"],
  mute: ["mute", "sharp", "sound", "volume", "volume-mute-sharp"],
  note: [
    "listening",
    "musical",
    "noise",
    "note",
    "play",
    "sharp",
    "sound",
    "musical-note-sharp"
  ],
  octoface: ["octocat", "brand"],
  organization: ["people", "group", "team"],
  package: ["gift", "package", "present", "skill", "craft", "freebie"],
  paintcan: ["style", "theme", "art", "color"],
  plug: ["hook", "webhook"],
  plus: ["new", "addition", "plus", "diff-added"],
  project: ["board", "kanban", "columns", "scrum"],
  question: [
    "?",
    "circle",
    "help",
    "information",
    "question",
    "sharp",
    "help-sharp"
  ],
  quote: ["quotation"],
  reply: ["reply all", "back"],
  repo: ["book", "journal", "repository"],
  report: ["stop", "block", "spam", "report"],
  rss: ["logo", "rss", "logo-rss"],
  ruby: [
    "text",
    "javascript",
    "html",
    "css",
    "php",
    "ruby",
    "coffeescript",
    "sass",
    "scss",
    "file-code"
  ],
  saved: ["saved", "bookmark"],
  skip: [
    "forward",
    "play",
    "right",
    "sharp",
    "skip",
    "play-skip-forward-sharp"
  ],
  smiley: ["emoji", "smile", "mood", "emotion"],
  squirrel: ["ship", "shipit", "launch"],
  tag: ["bookmark", "favorite", "save", "tag", "tab", "star"],
  tasklist: ["todo"],
  telescope: ["science", "space", "look", "view", "explore"],
  thumbsdown: ["thumb", "thumbsdown", "rejected", "dislike"],
  thumbsup: ["thumb", "thumbsup", "prop", "ship", "like"],
  tools: ["hammer", "options", "settings", "sharp", "tools", "hammer-sharp"],
  trashcan: ["garbage", "rubbish", "recycle", "delete"],
  unfold: ["unfold", "hide", "collapse", "up", "fold-up"],
  unmute: ["loud", "volume", "audio", "sound", "play"],
  unsaved: ["unsaved", "bookmark"],
  unverified: ["insecure", "untrusted", "signed"],
  verified: ["trusted", "secure", "trustworthy", "signed"],
  versions: ["history", "commits"],
  workflow: ["workflow", "actions", "workflow-all"],
  x: ["remove", "close", "delete"],
  zap: ["electricity", "lightning", "props", "like", "star", "save"],
  circle: [
    "?",
    "circle",
    "help",
    "information",
    "question",
    "sharp",
    "help-sharp"
  ],
  include: ["add", "circle", "include", "invite", "plus", "sharp", "add-sharp"],
  invite: ["add", "circle", "include", "invite", "plus", "sharp", "add-sharp"],
  outline: [
    "dudette",
    "female",
    "girl",
    "lady",
    "outline",
    "woman",
    "woman-outline"
  ],
  sharp: ["hammer", "options", "settings", "sharp", "tools", "hammer-sharp"],
  plane: ["paper", "plane", "sharp", "paper-plane-sharp"],
  boxes: ["albums", "boxes", "sharp", "slides", "square", "albums-sharp"],
  slides: ["albums", "boxes", "sharp", "slides", "square", "albums-sharp"],
  "!": [
    "!",
    "alert",
    "attention",
    "exclamation",
    "notice",
    "sharp",
    "warning",
    "alert-sharp"
  ],
  attention: [
    "!",
    "alert",
    "attention",
    "exclamation",
    "notice",
    "sharp",
    "warning",
    "alert-sharp"
  ],
  exclamation: [
    "!",
    "alert",
    "attention",
    "exclamation",
    "notice",
    "sharp",
    "warning",
    "alert-sharp"
  ],
  notice: [
    "!",
    "alert",
    "attention",
    "exclamation",
    "notice",
    "sharp",
    "warning",
    "alert-sharp"
  ],
  point: ["arrow", "point", "direction", "triangle-up"],
  american: ["american", "football", "sharp", "american-football-sharp"],
  data: ["disks", "data", "database"],
  metrics: [
    "analytics",
    "data",
    "metrics",
    "sharp",
    "track",
    "analytics-sharp"
  ],
  track: ["analytics", "data", "metrics", "sharp", "track", "analytics-sharp"],
  dark: ["dark", "moon", "night", "sharp", "sky", "moon-sharp"],
  levels: [
    "contrast",
    "dark",
    "images",
    "levels",
    "light",
    "settings",
    "sharp",
    "contrast-sharp"
  ],
  light: [
    "light",
    "sharp",
    "sky",
    "sunny",
    "weather",
    "whether",
    "sunny-sharp"
  ],
  applications: ["applications", "apps", "sharp", "apps-sharp"],
  email: ["email", "open", "mail-read"],
  box: ["box", "primitive-square"],
  catalog: ["archive", "email", "box", "catalog"],
  arrow: ["arrow", "point", "direction", "triangle-up"],
  back: ["reply all", "back", "reply"],
  chevron: ["chevron", "up", "triangle", "arrow", "chevron-up"],
  left: ["arrow", "point", "direction", "left", "line-arrow-left"],
  navigation: ["gps", "location", "navigation", "pin", "sharp", "pin-sharp"],
  down: ["arrow", "point", "direction", "down", "line-arrow-down"],
  direction: ["arrow", "point", "direction", "triangle-up"],
  forward: [
    "forward",
    "play",
    "right",
    "sharp",
    "skip",
    "play-skip-forward-sharp"
  ],
  right: [
    "forward",
    "play",
    "right",
    "sharp",
    "skip",
    "play-skip-forward-sharp"
  ],
  redo: ["arrow", "redo", "sharp", "arrow-redo-sharp"],
  undo: ["arrow", "sharp", "undo", "arrow-undo-sharp"],
  up: ["unfold", "hide", "collapse", "up", "fold-up"],
  "@": ["@", "at", "sharp", "at-sharp"],
  bar: ["bar", "chart", "sharp", "bar-chart-sharp"],
  chart: ["chart", "sharp", "stats", "stats-chart-sharp"],
  exercise: ["bicycle", "bike", "exercise", "sharp", "bicycle-sharp"],
  lifting: [
    "barbell",
    "exercise",
    "lifting",
    "sharp",
    "weight",
    "barbell-sharp"
  ],
  weight: [
    "barbell",
    "exercise",
    "lifting",
    "sharp",
    "weight",
    "barbell-sharp"
  ],
  battery: ["battery", "half", "sharp", "battery-half-sharp"],
  charging: ["battery", "charging", "sharp", "battery-charging-sharp"],
  dead: ["battery", "dead", "sharp", "battery-dead-sharp"],
  full: ["file", "full", "sharp", "tray", "file-tray-full-sharp"],
  half: ["favorite", "half", "rate", "sharp", "star", "star-half-sharp"],
  mixture: ["bubbles", "flask", "mixture", "potion", "sharp", "flask-sharp"],
  potion: ["bubbles", "flask", "mixture", "potion", "sharp", "flask-sharp"],
  experiment: [
    "beaker",
    "flask",
    "mixture",
    "potion",
    "experiment",
    "labs",
    "experimental",
    "feature",
    "test",
    "science",
    "education",
    "study",
    "development",
    "testing"
  ],
  labs: [
    "beaker",
    "flask",
    "mixture",
    "potion",
    "experiment",
    "labs",
    "experimental",
    "feature",
    "test",
    "science",
    "education",
    "study",
    "development",
    "testing"
  ],
  experimental: [
    "beaker",
    "flask",
    "mixture",
    "potion",
    "experiment",
    "labs",
    "experimental",
    "feature",
    "test",
    "science",
    "education",
    "study",
    "development",
    "testing"
  ],
  feature: [
    "beaker",
    "flask",
    "mixture",
    "potion",
    "experiment",
    "labs",
    "experimental",
    "feature",
    "test",
    "science",
    "education",
    "study",
    "development",
    "testing"
  ],
  test: [
    "beaker",
    "flask",
    "mixture",
    "potion",
    "experiment",
    "labs",
    "experimental",
    "feature",
    "test",
    "science",
    "education",
    "study",
    "development",
    "testing"
  ],
  science: ["science", "space", "look", "view", "explore", "telescope"],
  education: ["education", "learn", "teach", "mortar-board"],
  study: [
    "beaker",
    "flask",
    "mixture",
    "potion",
    "experiment",
    "labs",
    "experimental",
    "feature",
    "test",
    "science",
    "education",
    "study",
    "development",
    "testing"
  ],
  development: [
    "beaker",
    "flask",
    "mixture",
    "potion",
    "experiment",
    "labs",
    "experimental",
    "feature",
    "test",
    "science",
    "education",
    "study",
    "development",
    "testing"
  ],
  testing: [
    "beaker",
    "flask",
    "mixture",
    "potion",
    "experiment",
    "labs",
    "experimental",
    "feature",
    "test",
    "science",
    "education",
    "study",
    "development",
    "testing"
  ],
  hotel: ["bed", "hotel", "sharp", "sleep", "bed-sharp"],
  sleep: ["bed", "hotel", "sharp", "sleep", "bed-sharp"],
  drink: ["drink", "eat", "food", "pizza", "sharp", "pizza-sharp"],
  eat: ["eat", "restaurant", "sharp", "restaurant-sharp"],
  food: ["drink", "eat", "food", "pizza", "sharp", "pizza-sharp"],
  bike: ["bicycle", "bike", "exercise", "sharp", "bicycle-sharp"],
  connection: ["bars", "connection", "internet", "sharp", "wifi", "wifi-sharp"],
  heat: [
    "cold",
    "heat",
    "hot",
    "mercury",
    "sharp",
    "temperature",
    "thermometer",
    "thermometer-sharp"
  ],
  hot: ["hot", "live", "pulse", "rate", "graph", "trend", "line", "activity"],
  read: ["book", "read", "journal", "wiki", "readme"],
  wiki: ["book", "read", "journal", "wiki", "readme"],
  readme: ["book", "read", "journal", "wiki", "readme"],
  favorite: ["bookmark", "favorite", "save", "tag", "tab", "star"],
  tab: ["bookmark", "favorite", "save", "tag", "tab", "star"],
  organize: ["briefcase", "folder", "organize", "suitcase", "business"],
  suitcase: ["briefcase", "folder", "organize", "suitcase", "business"],
  develop: [
    "code",
    "develop",
    "download",
    "hacker",
    "program",
    "sharp",
    "code-download-sharp"
  ],
  error: ["no", "deny", "fail", "failure", "error", "bad", "circle-slash"],
  hacker: [
    "code",
    "develop",
    "download",
    "hacker",
    "program",
    "sharp",
    "code-download-sharp"
  ],
  program: [
    "code",
    "develop",
    "download",
    "hacker",
    "program",
    "sharp",
    "code-download-sharp"
  ],
  insect: ["bug", "develop", "error", "hacker", "program", "insect", "issue"],
  issue: ["bug", "develop", "error", "hacker", "program", "insect", "issue"],
  coffee: ["cafe", "coffee", "cup", "sharp", "cafe-sharp"],
  cup: ["cafe", "coffee", "cup", "sharp", "cafe-sharp"],
  arithmetic: ["arithmetic", "calculator", "math", "sharp", "calculator-sharp"],
  math: ["arithmetic", "calculator", "math", "sharp", "calculator-sharp"],
  date: ["calendar", "date", "month", "sharp", "week", "calendar-sharp"],
  month: ["calendar", "date", "month", "sharp", "week", "calendar-sharp"],
  week: ["calendar", "date", "month", "sharp", "week", "calendar-sharp"],
  day: [
    "calendar",
    "date",
    "month",
    "week",
    "time",
    "day",
    "year",
    "appointment"
  ],
  year: [
    "calendar",
    "date",
    "month",
    "week",
    "time",
    "day",
    "year",
    "appointment"
  ],
  appointment: [
    "calendar",
    "date",
    "month",
    "week",
    "time",
    "day",
    "year",
    "appointment"
  ],
  telephone: ["call", "sharp", "telephone", "call-sharp"],
  photo: ["photo", "picture", "image", "snapshot", "device-camera"],
  reverse: ["camera", "reverse", "sharp", "camera-reverse-sharp"],
  sport: ["car", "sharp", "sport", "car-sport-sharp"],
  $: [
    "$",
    "commerce",
    "items",
    "money",
    "pricetags",
    "sharp",
    "shopping",
    "pricetags-sharp"
  ],
  credit: [
    "$",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "price",
    "sharp",
    "shopping",
    "cash-sharp"
  ],
  debit: [
    "$",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "price",
    "sharp",
    "shopping",
    "cash-sharp"
  ],
  dollars: [
    "$",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "price",
    "sharp",
    "shopping",
    "cash-sharp"
  ],
  money: ["money", "billing", "payments", "transactions", "credit-card"],
  price: [
    "$",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "price",
    "sharp",
    "shopping",
    "cash-sharp"
  ],
  shopping: [
    "$",
    "commerce",
    "items",
    "money",
    "pricetags",
    "sharp",
    "shopping",
    "pricetags-sharp"
  ],
  caret: ["caret", "sharp", "up", "caret-up-sharp"],
  ellipses: ["chatbubble", "ellipses", "sharp", "chatbubble-ellipses-sharp"],
  talk: ["converse", "talk", "comment-discussion"],
  done: ["done", "complete", "issue-closed"],
  write: ["type", "keys", "write", "shortcuts", "keyboard"],
  delete: ["remove", "close", "delete", "x"],
  storage: ["cloud", "sharp", "storage", "upload", "cloud-upload-sharp"],
  weather: [
    "cloud",
    "rainy",
    "sharp",
    "water",
    "weather",
    "whether",
    "rainy-sharp"
  ],
  whether: [
    "cloud",
    "rainy",
    "sharp",
    "water",
    "weather",
    "whether",
    "rainy-sharp"
  ],
  install: [
    "cloud",
    "download",
    "storage",
    "save",
    "install",
    "get",
    "cloud-download"
  ],
  get: ["book", "journal", "get", "repo-pull"],
  offline: ["cloud", "offline", "sharp", "cloud-offline-sharp"],
  upload: ["cloud", "sharp", "storage", "upload", "cloud-upload-sharp"],
  put: ["book", "journal", "repository", "put", "repo-push"],
  export: ["download", "export", "sharp", "download-sharp"],
  overcast: [
    "cloudy",
    "lightning",
    "overcast",
    "rain",
    "sharp",
    "sky",
    "storm",
    "thunderstorm",
    "weather",
    "whether",
    "thunderstorm-sharp"
  ],
  night: ["dark", "moon", "night", "sharp", "sky", "moon-sharp"],
  brackets: ["code", "develop", "hacker", "program", "brackets"],
  slash: ["slash", "diff-ignored"],
  working: [
    "code",
    "develop",
    "hacker",
    "program",
    "sharp",
    "working",
    "code-working-sharp"
  ],
  color: ["style", "theme", "art", "color", "paintcan"],
  fill: ["color", "fill", "sharp", "color-fill-sharp"],
  palette: ["color", "palette", "sharp", "color-palette-sharp"],
  wand: ["color", "sharp", "wand", "color-wand-sharp"],
  directions: [
    "compass",
    "directions",
    "location",
    "navigation",
    "sharp",
    "compass-sharp"
  ],
  paper: ["email", "paper", "send", "sharp", "send-sharp"],
  edit: ["pencil", "edit", "change", "update", "write"],
  container: ["box", "container", "cube", "sharp", "square", "cube-sharp"],
  cd: ["cd", "disc", "sharp", "vinyl", "disc-sharp"],
  vinyl: ["cd", "disc", "sharp", "vinyl", "disc-sharp"],
  baby: ["baby", "bird", "birth", "egg", "sharp", "twitter", "egg-sharp"],
  bird: ["baby", "bird", "birth", "egg", "sharp", "twitter", "egg-sharp"],
  birth: ["baby", "bird", "birth", "egg", "sharp", "twitter", "egg-sharp"],
  twitter: ["logo", "twitter", "logo-twitter"],
  horizontal: ["horizontal", "sharp", "swap", "swap-horizontal-sharp"],
  vertical: ["ellipsis", "sharp", "vertical", "ellipsis-vertical-sharp"],
  exposed: ["exposed", "eye", "look", "see", "sharp", "view", "eye-sharp"],
  look: ["science", "space", "look", "view", "explore", "telescope"],
  see: ["out", "see", "more", "go", "to", "link-external"],
  view: ["science", "space", "look", "view", "explore", "telescope"],
  off: ["off", "sharp", "volume", "volume-off-sharp"],
  fast: ["fast", "food", "sharp", "fast-food-sharp"],
  dudette: [
    "dudette",
    "female",
    "girl",
    "lady",
    "sharp",
    "woman",
    "woman-sharp"
  ],
  girl: ["dudette", "female", "girl", "lady", "sharp", "woman", "woman-sharp"],
  lady: ["dudette", "female", "girl", "lady", "sharp", "woman", "woman-sharp"],
  tray: ["file", "sharp", "stacked", "tray", "file-tray-stacked-sharp"],
  stacked: ["file", "sharp", "stacked", "tray", "file-tray-stacked-sharp"],
  finger: ["finger", "print", "sharp", "finger-print-sharp"],
  marker: ["marker", "milestone"],
  fire: ["fire", "flame", "heat", "hot", "sharp", "flame-sharp"],
  burn: ["fire", "flame", "heat", "hot", "burn", "trending"],
  trending: ["sharp", "trending", "up", "trending-up-sharp"],
  lightning: [
    "electricity",
    "lightning",
    "props",
    "like",
    "star",
    "save",
    "zap"
  ],
  bubbles: ["bubbles", "flask", "mixture", "potion", "sharp", "flask-sharp"],
  soccer: ["football", "sharp", "soccer", "football-sharp"],
  sort: ["mover", "drap", "drop", "sort", "grabber"],
  controller: ["controller", "game", "sharp", "game-controller-sharp"],
  game: ["team", "game", "basketball", "jersey"],
  present: ["gift", "package", "present", "skill", "craft", "freebie"],
  skill: ["gift", "package", "present", "skill", "craft", "freebie"],
  craft: ["gift", "package", "present", "skill", "craft", "freebie"],
  freebie: ["gift", "package", "present", "skill", "craft", "freebie"],
  branch: ["branch", "git", "sharp", "git-branch-sharp"],
  git: ["commit", "git", "save", "git-commit"],
  fork: ["branch", "git", "fork", "duplicate", "git-branch"],
  commit: ["commit", "git", "save", "git-commit"],
  compare: ["difference", "changes", "compare", "diff"],
  difference: ["difference", "changes", "compare", "diff"],
  changes: ["diff", "changes", "request", "request-changes"],
  merge: ["git", "merge", "sharp", "git-merge-sharp"],
  join: ["git", "merge", "join", "git-merge"],
  network: ["git", "network", "sharp", "git-network-sharp"],
  pull: ["git", "pull", "request", "sharp", "git-pull-request-sharp"],
  request: ["diff", "changes", "request", "request-changes"],
  review: ["git", "pull", "request", "review", "git-pull-request"],
  reading: [
    "glasses",
    "look",
    "reading",
    "see",
    "sharp",
    "steve",
    "glasses-sharp"
  ],
  steve: [
    "glasses",
    "look",
    "reading",
    "see",
    "sharp",
    "steve",
    "glasses-sharp"
  ],
  internet: ["bars", "connection", "internet", "sharp", "wifi", "wifi-sharp"],
  world: [
    "globe",
    "home",
    "nature",
    "planet",
    "sharp",
    "space",
    "world",
    "planet-sharp"
  ],
  hand: ["hand", "right", "sharp", "hand-right-sharp"],
  fun: ["fun", "good", "happy", "like", "sharp", "smile", "yes", "happy-sharp"],
  good: [
    "fun",
    "good",
    "happy",
    "like",
    "sharp",
    "smile",
    "yes",
    "happy-sharp"
  ],
  like: ["electricity", "lightning", "props", "like", "star", "save", "zap"],
  smile: ["emoji", "smile", "mood", "emotion", "smiley"],
  yes: ["mark", "yes", "confirm", "accept", "ok", "success", "check"],
  chip: ["chip", "hardware", "sharp", "hardware-chip-sharp"],
  hardware: ["developer", "hardware", "electricity", "circuit-board"],
  love: ["heart", "love", "sharp", "heart-sharp"],
  beat: ["heart", "love", "outline", "beat", "heart-outline"],
  dislike: ["thumb", "thumbsdown", "rejected", "dislike"],
  "?": [
    "?",
    "circle",
    "help",
    "information",
    "question",
    "sharp",
    "help-sharp"
  ],
  buoy: ["?", "buoy", "help", "question", "sharp", "help-buoy-sharp"],
  house: ["home", "house", "sharp", "home-sharp"],
  welcome: ["home", "house", "welcome", "index", "building"],
  index: ["home", "house", "welcome", "index", "building"],
  building: ["home", "house", "welcome", "index", "building"],
  cream: ["cream", "ice", "sharp", "ice-cream-sharp"],
  ice: ["cream", "ice", "sharp", "ice-cream-sharp"],
  forever: ["forever", "infinite", "loop", "sharp", "infinite-sharp"],
  loop: ["sync", "cycle", "refresh", "loop"],
  knowledge: [
    "circle",
    "help",
    "information",
    "knowledge",
    "sharp",
    "information-sharp"
  ],
  access: ["access", "key", "sharp", "key-sharp"],
  secure: ["trusted", "secure", "trustworthy", "signed", "verified"],
  safe: ["access", "key", "lock", "secure", "safe"],
  type: ["type", "keys", "write", "shortcuts", "keyboard"],
  apple: ["apple", "appstore", "logo", "logo-apple-appstore"],
  macbook: ["apple", "laptop", "macbook", "osx", "sharp", "laptop-sharp"],
  osx: ["apple", "laptop", "macbook", "osx", "sharp", "laptop-sharp"],
  green: ["green", "leaf", "nature", "plant", "recycle", "sharp", "leaf-sharp"],
  nature: [
    "globe",
    "home",
    "nature",
    "planet",
    "sharp",
    "space",
    "world",
    "planet-sharp"
  ],
  plant: ["green", "leaf", "nature", "plant", "recycle", "sharp", "leaf-sharp"],
  recycle: ["garbage", "rubbish", "recycle", "delete", "trashcan"],
  anchor: ["anchor", "attach", "chain", "href", "link", "sharp", "link-sharp"],
  chain: ["anchor", "attach", "chain", "href", "link", "sharp", "link-sharp"],
  href: ["anchor", "attach", "chain", "href", "link", "sharp", "link-sharp"],
  connect: [
    "anchor",
    "attach",
    "chain",
    "href",
    "link",
    "connect",
    "hyperlink"
  ],
  hyperlink: [
    "anchor",
    "attach",
    "chain",
    "href",
    "link",
    "connect",
    "hyperlink"
  ],
  gps: ["gps", "location", "navigation", "pin", "sharp", "pin-sharp"],
  maps: ["gps", "locate", "maps", "navigate", "sharp", "locate-sharp"],
  closed: ["captioning", "closed", "logo", "logo-closed-captioning"],
  login: ["login", "sharp", "signin", "log-in-sharp"],
  signin: ["login", "sharp", "signin", "log-in-sharp"],
  logout: ["logout", "sharp", "signout", "log-out-sharp"],
  signout: ["logout", "sharp", "signout", "log-out-sharp"],
  amazon: ["amazon", "logo", "logo-amazon"],
  logo: ["logo", "rss", "logo-rss"],
  amplify: ["amplify", "logo", "logo-amplify"],
  android: ["android", "logo", "logo-android"],
  angular: ["angular", "logo", "logo-angular"],
  appstore: ["apple", "appstore", "logo", "logo-apple-appstore"],
  behance: ["behance", "logo", "logo-behance"],
  bitbucket: ["bitbucket", "logo", "logo-bitbucket"],
  bitcoin: ["bitcoin", "logo", "logo-bitcoin"],
  buffer: ["buffer", "logo", "logo-buffer"],
  capacitor: ["capacitor", "logo", "logo-capacitor"],
  chrome: ["chrome", "logo", "logo-chrome"],
  captioning: ["captioning", "closed", "logo", "logo-closed-captioning"],
  codepen: ["codepen", "logo", "logo-codepen"],
  css3: ["css3", "logo", "logo-css3"],
  designernews: ["designernews", "logo", "logo-designernews"],
  docker: ["docker", "logo", "logo-docker"],
  dribbble: ["dribbble", "logo", "logo-dribbble"],
  dropbox: ["dropbox", "logo", "logo-dropbox"],
  edge: ["edge", "logo", "logo-edge"],
  electron: ["electron", "logo", "logo-electron"],
  euro: ["euro", "logo", "logo-euro"],
  facebook: ["facebook", "logo", "logo-facebook"],
  firebase: ["firebase", "logo", "logo-firebase"],
  firefox: ["firefox", "logo", "logo-firefox"],
  flickr: ["flickr", "logo", "logo-flickr"],
  foursquare: ["foursquare", "logo", "logo-foursquare"],
  github: ["octocat", "brand", "github", "logo", "mark-github"],
  brand: ["octocat", "brand", "octoface"],
  gitlab: ["gitlab", "logo", "logo-gitlab"],
  google: ["google", "logo", "playstore", "logo-google-playstore"],
  playstore: ["google", "logo", "playstore", "logo-google-playstore"],
  hackernews: ["hackernews", "logo", "logo-hackernews"],
  html5: ["html5", "logo", "logo-html5"],
  instagram: ["instagram", "logo", "logo-instagram"],
  ionic: ["ionic", "logo", "logo-ionic"],
  ionitron: ["ionitron", "logo", "logo-ionitron"],
  javascript: [
    "text",
    "javascript",
    "html",
    "css",
    "php",
    "ruby",
    "coffeescript",
    "sass",
    "scss",
    "file-code"
  ],
  laravel: ["laravel", "logo", "logo-laravel"],
  linkedin: ["linkedin", "logo", "logo-linkedin"],
  medium: ["medium", "sharp", "volume", "volume-medium-sharp"],
  no: ["no", "deny", "fail", "failure", "error", "bad", "circle-slash"],
  smoking: ["logo", "no", "smoking", "logo-no-smoking"],
  nodejs: ["logo", "nodejs", "logo-nodejs"],
  npm: ["logo", "npm", "logo-npm"],
  octocat: ["octocat", "brand", "octoface"],
  paypal: ["logo", "paypal", "logo-paypal"],
  pinterest: ["logo", "pinterest", "logo-pinterest"],
  playstation: ["logo", "playstation", "logo-playstation"],
  pwa: ["logo", "pwa", "logo-pwa"],
  python: ["logo", "python", "logo-python"],
  react: ["logo", "react", "logo-react"],
  reddit: ["logo", "reddit", "logo-reddit"],
  sass: [
    "text",
    "javascript",
    "html",
    "css",
    "php",
    "ruby",
    "coffeescript",
    "sass",
    "scss",
    "file-code"
  ],
  skype: ["logo", "skype", "logo-skype"],
  slack: ["logo", "slack", "logo-slack"],
  snapchat: ["logo", "snapchat", "logo-snapchat"],
  soundcloud: ["logo", "soundcloud", "logo-soundcloud"],
  stackoverflow: ["logo", "stackoverflow", "logo-stackoverflow"],
  steam: ["logo", "steam", "logo-steam"],
  stencil: ["logo", "stencil", "logo-stencil"],
  tiktok: ["logo", "tiktok", "logo-tiktok"],
  tumblr: ["logo", "tumblr", "logo-tumblr"],
  tux: ["logo", "tux", "logo-tux"],
  twitch: ["logo", "twitch", "logo-twitch"],
  usd: ["logo", "usd", "logo-usd"],
  venmo: ["logo", "venmo", "logo-venmo"],
  vimeo: ["logo", "vimeo", "logo-vimeo"],
  vk: ["logo", "vk", "logo-vk"],
  vue: ["logo", "vue", "logo-vue"],
  component: ["component", "logo", "web", "logo-web-component"],
  web: ["window", "web", "browser"],
  whatsapp: ["logo", "whatsapp", "logo-whatsapp"],
  windows: ["logo", "windows", "logo-windows"],
  wordpress: ["logo", "wordpress", "logo-wordpress"],
  xbox: ["logo", "xbox", "logo-xbox"],
  xing: ["logo", "xing", "logo-xing"],
  yahoo: ["logo", "yahoo", "logo-yahoo"],
  yen: ["logo", "yen", "logo-yen"],
  youtube: ["logo", "youtube", "logo-youtube"],
  attraction: ["attraction", "magnet", "sharp", "sticky", "magnet-sharp"],
  sticky: ["attraction", "magnet", "sharp", "sticky", "magnet-sharp"],
  unread: ["circle", "dot", "unread", "primitive-dot-stroke"],
  boy: ["boy", "dude", "guy", "male", "man", "sharp", "man-sharp"],
  dude: ["boy", "dude", "guy", "male", "man", "sharp", "man-sharp"],
  guy: ["boy", "dude", "guy", "male", "man", "sharp", "man-sharp"],
  case: [
    "case",
    "disease",
    "firstaid",
    "health",
    "medkit",
    "sharp",
    "sick",
    "medkit-sharp"
  ],
  disease: [
    "case",
    "disease",
    "firstaid",
    "health",
    "medkit",
    "sharp",
    "sick",
    "medkit-sharp"
  ],
  firstaid: [
    "case",
    "disease",
    "firstaid",
    "health",
    "medkit",
    "sharp",
    "sick",
    "medkit-sharp"
  ],
  health: [
    "case",
    "disease",
    "firstaid",
    "health",
    "medkit",
    "sharp",
    "sick",
    "medkit-sharp"
  ],
  sick: [
    "case",
    "disease",
    "firstaid",
    "health",
    "medkit",
    "sharp",
    "sick",
    "medkit-sharp"
  ],
  bullhorn: ["megaphone", "bullhorn", "loud", "shout", "broadcast"],
  loud: ["loud", "volume", "audio", "sound", "play", "unmute"],
  shout: ["megaphone", "bullhorn", "loud", "shout", "broadcast"],
  noise: [
    "listening",
    "musical",
    "noise",
    "note",
    "play",
    "sharp",
    "sound",
    "musical-note-sharp"
  ],
  sound: ["loud", "volume", "audio", "sound", "play", "unmute"],
  speaker: ["mic", "noise", "sharp", "sound", "speaker", "talk", "mic-sharp"],
  sky: [
    "cloudy",
    "lightning",
    "overcast",
    "rain",
    "sharp",
    "sky",
    "storm",
    "thunderstorm",
    "weather",
    "whether",
    "thunderstorm-sharp"
  ],
  listening: [
    "listening",
    "musical",
    "noise",
    "note",
    "play",
    "sharp",
    "sound",
    "musical-note-sharp"
  ],
  musical: [
    "listening",
    "musical",
    "noise",
    "note",
    "play",
    "sharp",
    "sound",
    "musical-note-sharp"
  ],
  notes: [
    "listening",
    "musical",
    "noise",
    "notes",
    "play",
    "sharp",
    "sound",
    "musical-notes-sharp"
  ],
  danger: ["danger", "hazard", "nuclear", "sharp", "warning", "nuclear-sharp"],
  hazard: ["danger", "hazard", "nuclear", "sharp", "warning", "nuclear-sharp"],
  partly: ["partly", "sharp", "sunny", "partly-sunny-sharp"],
  break: ["break", "freeze", "hold", "music", "pause", "sharp", "pause-sharp"],
  freeze: ["break", "freeze", "hold", "music", "pause", "sharp", "pause-sharp"],
  hold: ["break", "freeze", "hold", "music", "pause", "sharp", "pause-sharp"],
  music: ["music", "radio", "sharp", "radio-sharp"],
  change: ["pencil", "edit", "change", "update", "write"],
  update: ["pencil", "edit", "change", "update", "write"],
  head: ["head", "human", "person", "sharp", "staff", "users", "person-sharp"],
  human: ["head", "human", "person", "sharp", "staff", "users", "person-sharp"],
  stalker: [
    "head",
    "human",
    "people",
    "person",
    "sharp",
    "stalker",
    "users",
    "people-sharp"
  ],
  users: ["head", "human", "person", "sharp", "staff", "users", "person-sharp"],
  member: [
    "add",
    "head",
    "human",
    "member",
    "new",
    "person",
    "sharp",
    "staff",
    "users",
    "person-add-sharp"
  ],
  new: ["book", "new", "template", "repo-template-private"],
  staff: [
    "rocket",
    "staff",
    "stafftools",
    "blast",
    "off",
    "space",
    "launch",
    "ship"
  ],
  landscape: ["landscape", "sharp", "tablet", "tablet-landscape-sharp"],
  phone: ["phone", "iphone", "cellphone", "device-mobile"],
  portrait: ["portrait", "sharp", "tablet", "tablet-portrait-sharp"],
  pie: ["chart", "pie", "sharp", "pie-chart-sharp"],
  space: ["science", "space", "look", "view", "explore", "telescope"],
  award: [
    "award",
    "compete",
    "competition",
    "lose",
    "sharp",
    "trophy",
    "win",
    "trophy-sharp"
  ],
  compete: [
    "award",
    "compete",
    "competition",
    "lose",
    "sharp",
    "trophy",
    "win",
    "trophy-sharp"
  ],
  competition: [
    "award",
    "compete",
    "competition",
    "lose",
    "sharp",
    "trophy",
    "win",
    "trophy-sharp"
  ],
  lose: [
    "award",
    "compete",
    "competition",
    "lose",
    "sharp",
    "trophy",
    "win",
    "trophy-sharp"
  ],
  win: [
    "award",
    "compete",
    "competition",
    "lose",
    "sharp",
    "trophy",
    "win",
    "trophy-sharp"
  ],
  on: ["button", "on", "radio", "sharp", "radio-button-on-sharp"],
  commerce: [
    "$",
    "commerce",
    "items",
    "money",
    "pricetags",
    "sharp",
    "shopping",
    "pricetags-sharp"
  ],
  items: ["bullet", "point", "tasks", "todo", "items", "list-unordered"],
  live: ["hot", "live", "pulse", "rate", "graph", "trend", "line", "activity"],
  rate: ["hot", "live", "pulse", "rate", "graph", "trend", "line", "activity"],
  trend: ["hot", "live", "pulse", "rate", "graph", "trend", "line", "activity"],
  line: ["hot", "live", "pulse", "rate", "graph", "trend", "line", "activity"],
  activity: [
    "hot",
    "live",
    "pulse",
    "rate",
    "graph",
    "trend",
    "line",
    "activity"
  ],
  qr: ["code", "qr", "sharp", "qr-code-sharp"],
  button: ["button", "on", "radio", "sharp", "radio-button-on-sharp"],
  tape: ["film", "recording", "sharp", "tape", "voicemail", "recording-sharp"],
  voicemail: [
    "film",
    "recording",
    "sharp",
    "tape",
    "voicemail",
    "recording-sharp"
  ],
  renew: [
    "circle",
    "refresh",
    "reload",
    "renew",
    "reset",
    "sharp",
    "refresh-sharp"
  ],
  reset: [
    "circle",
    "refresh",
    "reload",
    "renew",
    "reset",
    "sharp",
    "refresh-sharp"
  ],
  minus: ["circle", "minus", "remove", "sharp", "subtract", "remove-sharp"],
  subtract: ["circle", "minus", "remove", "sharp", "subtract", "remove-sharp"],
  four: ["four", "reorder", "sharp", "reorder-four-sharp"],
  reorder: ["reorder", "sharp", "two", "reorder-two-sharp"],
  three: ["reorder", "sharp", "three", "reorder-three-sharp"],
  two: ["reorder", "sharp", "two", "reorder-two-sharp"],
  return: ["return", "no-newline"],
  stafftools: [
    "rocket",
    "staff",
    "stafftools",
    "blast",
    "off",
    "space",
    "launch",
    "ship"
  ],
  blast: [
    "rocket",
    "staff",
    "stafftools",
    "blast",
    "off",
    "space",
    "launch",
    "ship"
  ],
  launch: ["ship", "shipit", "launch", "squirrel"],
  ship: ["thumb", "thumbsup", "prop", "ship", "like"],
  bad: ["no", "deny", "fail", "failure", "error", "bad", "circle-slash"],
  cry: ["bad", "cry", "no", "sad", "sharp", "sad-sharp"],
  glass: ["glass", "sharp", "wine", "wine-sharp"],
  magnifying: ["glass", "magnifying", "search", "sharp", "search-sharp"],
  computers: ["server", "computers", "racks", "ops"],
  racks: ["server", "computers", "racks", "ops"],
  ops: ["terminal", "code", "ops", "shell"],
  social: ["share", "sharp", "social", "share-social-sharp"],
  security: ["security", "shield", "protection", "fail", "shield-x"],
  protection: ["security", "shield", "protection", "fail", "shield-x"],
  random: ["random", "sharp", "shuffle", "shuffle-sharp"],
  cold: [
    "cold",
    "heat",
    "hot",
    "mercury",
    "sharp",
    "temperature",
    "thermometer",
    "thermometer-sharp"
  ],
  drive: [
    "drive",
    "level",
    "sharp",
    "speed",
    "speedometer",
    "speedometer-sharp"
  ],
  level: [
    "drive",
    "level",
    "sharp",
    "speed",
    "speedometer",
    "speedometer-sharp"
  ],
  speed: ["speed", "dial", "dashboard"],
  stats: ["chart", "sharp", "stats", "stats-chart-sharp"],
  block: ["stop", "block", "spam", "report"],
  spam: ["stop", "block", "spam", "report"],
  swap: ["sharp", "swap", "vertical", "swap-vertical-sharp"],
  cycle: ["sync", "cycle", "refresh", "loop"],
  tablet: ["portrait", "sharp", "tablet", "tablet-portrait-sharp"],
  shell: ["terminal", "code", "ops", "shell"],
  mercury: [
    "cold",
    "heat",
    "hot",
    "mercury",
    "sharp",
    "temperature",
    "thermometer",
    "thermometer-sharp"
  ],
  temperature: [
    "cold",
    "heat",
    "hot",
    "mercury",
    "sharp",
    "temperature",
    "thermometer",
    "thermometer-sharp"
  ],
  thumbs: ["sharp", "thumbs", "up", "thumbs-up-sharp"],
  rain: [
    "dry",
    "rain",
    "sharp",
    "shelter",
    "umbrella",
    "wet",
    "umbrella-sharp"
  ],
  storm: [
    "cloudy",
    "lightning",
    "overcast",
    "rain",
    "sharp",
    "sky",
    "storm",
    "thunderstorm",
    "weather",
    "whether",
    "thunderstorm-sharp"
  ],
  hour: [
    "clock",
    "hour",
    "minute",
    "second",
    "sharp",
    "time",
    "watch",
    "time-sharp"
  ],
  minute: [
    "clock",
    "hour",
    "minute",
    "second",
    "sharp",
    "time",
    "watch",
    "time-sharp"
  ],
  second: [
    "clock",
    "hour",
    "minute",
    "second",
    "sharp",
    "time",
    "watch",
    "time-sharp"
  ],
  switch: ["sharp", "switch", "toggle", "toggle-sharp"],
  sign: ["sharp", "sign", "trail", "trail-sign-sharp"],
  trail: ["sharp", "sign", "trail", "trail-sign-sharp"],
  bin: ["bin", "sharp", "trash", "trash-bin-sharp"],
  television: ["sharp", "television", "tv", "tv-sharp"],
  dry: ["dry", "rain", "sharp", "shelter", "umbrella", "wet", "umbrella-sharp"],
  shelter: [
    "dry",
    "rain",
    "sharp",
    "shelter",
    "umbrella",
    "wet",
    "umbrella-sharp"
  ],
  wet: ["dry", "rain", "sharp", "shelter", "umbrella", "wet", "umbrella-sharp"],
  movie: ["camera", "film", "movie", "sharp", "videocam", "videocam-sharp"],
  high: ["high", "sharp", "volume", "volume-high-sharp"],
  volume: ["loud", "volume", "audio", "sound", "play", "unmute"],
  low: ["low", "sharp", "volume", "volume-low-sharp"],
  bars: ["bars", "connection", "internet", "sharp", "wifi", "wifi-sharp"],
  notification: ["notification", "bell"],
  window: ["window", "web", "browser"],
  mark: ["mark", "yes", "confirm", "accept", "ok", "success", "check"],
  confirm: ["mark", "yes", "confirm", "accept", "ok", "success", "check"],
  accept: ["mark", "yes", "confirm", "accept", "ok", "success", "check"],
  ok: ["mark", "yes", "confirm", "accept", "ok", "success", "check"],
  success: [
    "security",
    "shield",
    "protection",
    "check",
    "success",
    "shield-check"
  ],
  todo: ["todo", "tasklist"],
  tasks: ["bullet", "point", "tasks", "todo", "items", "list-unordered"],
  deny: ["no", "deny", "fail", "failure", "error", "bad", "circle-slash"],
  fail: ["security", "shield", "protection", "fail", "shield-x"],
  failure: ["no", "deny", "fail", "failure", "error", "bad", "circle-slash"],
  developer: ["developer", "hardware", "electricity", "circuit-board"],
  electricity: [
    "electricity",
    "lightning",
    "props",
    "like",
    "star",
    "save",
    "zap"
  ],
  paste: ["copy", "paste", "save", "capture", "clipboard", "clippy"],
  capture: ["copy", "paste", "save", "capture", "clipboard", "clippy"],
  speak: ["speak", "bubble", "comment"],
  bubble: ["speak", "bubble", "comment"],
  converse: ["converse", "talk", "comment-discussion"],
  billing: ["money", "billing", "payments", "transactions", "credit-card"],
  payments: ["money", "billing", "payments", "transactions", "credit-card"],
  transactions: ["money", "billing", "payments", "transactions", "credit-card"],
  hyphen: ["hyphen", "range", "dash"],
  range: ["hyphen", "range", "dash"],
  dial: ["speed", "dial", "dashboard"],
  disks: ["disks", "data", "database"],
  dependency: ["dependency", "dependent", "file"],
  clone: ["clone", "download", "desktop-download"],
  picture: ["photo", "picture", "image", "snapshot", "device-camera"],
  snapshot: ["photo", "picture", "image", "snapshot", "device-camera"],
  media: ["watch", "view", "media", "stream", "device-camera-video"],
  stream: ["watch", "view", "media", "stream", "device-camera-video"],
  computer: ["computer", "monitor", "device-desktop"],
  monitor: ["computer", "monitor", "device-desktop"],
  iphone: ["phone", "iphone", "cellphone", "device-mobile"],
  cellphone: ["phone", "iphone", "cellphone", "device-mobile"],
  addition: ["new", "addition", "plus", "diff-added"],
  dot: ["circle", "dot", "unread", "primitive-dot-stroke"],
  changed: ["dot", "changed", "updated", "diff-modified"],
  updated: ["dot", "changed", "updated", "diff-modified"],
  deleted: ["deleted", "subtracted", "dash", "diff-removed"],
  subtracted: ["deleted", "subtracted", "dash", "diff-removed"],
  moved: ["moved", "arrow", "diff-renamed"],
  hidden: ["hidden", "invisible", "concealed", "", "eye-closed"],
  invisible: ["hidden", "invisible", "concealed", "", "eye-closed"],
  concealed: ["hidden", "invisible", "concealed", "", "eye-closed"],
  "": ["hidden", "invisible", "concealed", "", "eye-closed"],
  video: ["image", "video", "audio", "file-media"],
  word: ["image", "video", "word", "powerpoint", "excel", "file-binary"],
  powerpoint: ["image", "video", "word", "powerpoint", "excel", "file-binary"],
  excel: ["image", "video", "word", "powerpoint", "excel", "file-binary"],
  html: [
    "text",
    "javascript",
    "html",
    "css",
    "php",
    "ruby",
    "coffeescript",
    "sass",
    "scss",
    "file-code"
  ],
  css: [
    "text",
    "javascript",
    "html",
    "css",
    "php",
    "ruby",
    "coffeescript",
    "sass",
    "scss",
    "file-code"
  ],
  php: [
    "text",
    "javascript",
    "html",
    "css",
    "php",
    "ruby",
    "coffeescript",
    "sass",
    "scss",
    "file-code"
  ],
  coffeescript: [
    "text",
    "javascript",
    "html",
    "css",
    "php",
    "ruby",
    "coffeescript",
    "sass",
    "scss",
    "file-code"
  ],
  scss: [
    "text",
    "javascript",
    "html",
    "css",
    "php",
    "ruby",
    "coffeescript",
    "sass",
    "scss",
    "file-code"
  ],
  audio: ["loud", "volume", "audio", "sound", "play", "unmute"],
  adobe: ["adobe", "file-pdf"],
  subfolder: ["folder", "subfolder", "link", "alias", "file-symlink-directory"],
  alias: ["link", "alias", "file-symlink-file"],
  compress: ["compress", "archive", "file-zip"],
  hide: ["unfold", "hide", "collapse", "up", "fold-up"],
  collapse: ["unfold", "hide", "collapse", "up", "fold-up"],
  secret: ["gist", "secret", "private", "gist-secret"],
  private: ["gist", "secret", "private", "gist-secret"],
  board: ["board", "workflow", "action", "automation", "github-action"],
  action: ["board", "workflow", "action", "automation", "github-action"],
  automation: ["board", "workflow", "action", "automation", "github-action"],
  mover: ["mover", "drap", "drop", "sort", "grabber"],
  drap: ["mover", "drap", "drop", "sort", "grabber"],
  drop: ["mover", "drap", "drop", "sort", "grabber"],
  past: ["time", "past", "revert", "back", "history"],
  revert: ["time", "past", "revert", "back", "history"],
  hr: ["hr", "horizontal-rule"],
  robot: ["robot", "bot", "hubot"],
  bot: ["robot", "bot", "hubot"],
  messages: ["mail", "todo", "new", "messages", "inbox"],
  unlimited: ["unlimited", "infinite", "infinity"],
  "internal, repo, repository": ["internal, repo, repository", "internal-repo"],
  complete: ["done", "complete", "issue-closed"],
  regression: ["regression", "issue-reopened"],
  font: ["font", "size", "text", "text-size"],
  style: ["style", "theme", "art", "color", "paintcan"],
  team: ["people", "group", "team", "organization"],
  kebab: ["kebab", "dot", "menu", "more", "kebab-vertical"],
  more: ["add", "new", "more", "small", "plus-small"],
  keys: ["type", "keys", "write", "shortcuts", "keyboard"],
  shortcuts: ["type", "keys", "write", "shortcuts", "keyboard"],
  legal: ["legal", "bill", "law"],
  bill: ["legal", "bill", "law"],
  idea: ["idea", "light-bulb"],
  out: ["out", "see", "more", "go", "to", "link-external"],
  go: ["out", "see", "more", "go", "to", "link-external"],
  to: ["out", "see", "more", "go", "to", "link-external"],
  numbers: ["numbers", "tasks", "todo", "items", "list-ordered"],
  bullet: ["bullet", "point", "tasks", "todo", "items", "list-unordered"],
  ping: ["at", "ping", "mention"],
  reflect: ["reflect", "mirror"],
  learn: ["education", "learn", "teach", "mortar-board"],
  teach: ["education", "learn", "teach", "mortar-board"],
  snowflake: ["star", "snowflake", "asterisk", "north-star"],
  asterisk: ["star", "snowflake", "asterisk", "north-star"],
  group: ["people", "group", "team", "organization"],
  theme: ["style", "theme", "art", "color", "paintcan"],
  art: ["style", "theme", "art", "color", "paintcan"],
  hook: ["hook", "webhook", "plug"],
  webhook: ["hook", "webhook", "plug"],
  small: ["add", "new", "more", "small", "plus-small"],
  kanban: ["board", "kanban", "columns", "scrum", "project"],
  columns: ["board", "kanban", "columns", "scrum", "project"],
  scrum: ["board", "kanban", "columns", "scrum", "project"],
  quotation: ["quotation", "quote"],
  "reply all": ["reply all", "back", "reply"],
  repository: ["book", "journal", "repository", "put", "repo-push"],
  template: ["book", "new", "template", "repo-template-private"],
  fullscreen: ["fullscreen", "expand", "exit", "screen-normal"],
  protect: ["protect", "shield", "lock", "shield-lock"],
  door: ["door", "arrow", "direction", "leave", "log out", "sign-out"],
  "log in": ["door", "arrow", "direction", "enter", "log in", "sign-in"],
  leave: ["door", "arrow", "direction", "leave", "log out", "sign-out"],
  "log out": ["door", "arrow", "direction", "leave", "log out", "sign-out"],
  emoji: ["emoji", "smile", "mood", "emotion", "smiley"],
  mood: ["emoji", "smile", "mood", "emotion", "smiley"],
  emotion: ["emoji", "smile", "mood", "emotion", "smiley"],
  shipit: ["ship", "shipit", "launch", "squirrel"],
  explore: ["science", "space", "look", "view", "explore", "telescope"],
  size: ["font", "size", "text", "text-size"],
  hamburger: ["hamburger", "menu", "dropdown", "three-bars"],
  dropdown: ["hamburger", "menu", "dropdown", "three-bars"],
  thumb: ["thumb", "thumbsup", "prop", "ship", "like"],
  rejected: ["thumb", "thumbsdown", "rejected", "dislike"],
  prop: ["thumb", "thumbsup", "prop", "ship", "like"],
  garbage: ["garbage", "rubbish", "recycle", "delete", "trashcan"],
  rubbish: ["garbage", "rubbish", "recycle", "delete", "trashcan"],
  insecure: ["insecure", "untrusted", "signed", "unverified"],
  untrusted: ["insecure", "untrusted", "signed", "unverified"],
  signed: ["trusted", "secure", "trustworthy", "signed", "verified"],
  trusted: ["trusted", "secure", "trustworthy", "signed", "verified"],
  trustworthy: ["trusted", "secure", "trustworthy", "signed", "verified"],
  commits: ["history", "commits", "versions"],
  actions: ["workflow", "actions", "workflow-all"],
  props: ["electricity", "lightning", "props", "like", "star", "save", "zap"]
};
