module.exports = {
  add: ["add", "circle", "include", "invite", "plus"],
  "add-circle": ["add", "circle", "include", "invite", "plus"],
  "add-circle-outline": [
    "add",
    "circle",
    "include",
    "invite",
    "outline",
    "plus"
  ],
  "add-circle-sharp": ["add", "circle", "include", "invite", "plus", "sharp"],
  "add-outline": ["add", "outline"],
  "add-sharp": ["add", "circle", "include", "invite", "plus", "sharp"],
  airplane: ["airplane", "plane"],
  "airplane-outline": ["airplane", "outline", "plane"],
  "airplane-sharp": ["airplane", "plane", "sharp"],
  alarm: ["alarm", "clock", "time"],
  "alarm-outline": ["alarm", "clock", "outline", "time"],
  "alarm-sharp": ["alarm", "clock", "sharp", "time"],
  albums: ["albums", "boxes", "slides", "square"],
  "albums-outline": ["albums", "boxes", "outline", "slides", "square"],
  "albums-sharp": ["albums", "boxes", "sharp", "slides", "square"],
  alert: [
    "!",
    "alert",
    "attention",
    "exclamation",
    "notice",
    "warning",
    "triangle",
    "point"
  ],
  "alert-circle": [
    "!",
    "alert",
    "attention",
    "circle",
    "exclamation",
    "notice",
    "warning"
  ],
  "alert-circle-outline": [
    "!",
    "alert",
    "attention",
    "circle",
    "exclamation",
    "notice",
    "outline",
    "warning"
  ],
  "alert-circle-sharp": [
    "!",
    "alert",
    "attention",
    "circle",
    "exclamation",
    "notice",
    "sharp",
    "warning"
  ],
  "alert-outline": ["alert", "outline"],
  "alert-sharp": [
    "!",
    "alert",
    "attention",
    "exclamation",
    "notice",
    "sharp",
    "warning"
  ],
  "american-football": ["american", "football"],
  "american-football-outline": ["american", "football", "outline"],
  "american-football-sharp": ["american", "football", "sharp"],
  analytics: ["analytics", "data", "metrics", "track"],
  "analytics-outline": ["analytics", "data", "metrics", "outline", "track"],
  "analytics-sharp": ["analytics", "data", "metrics", "sharp", "track"],
  aperture: ["aperture", "dark", "images", "levels", "light", "settings"],
  "aperture-outline": [
    "aperture",
    "dark",
    "images",
    "levels",
    "light",
    "outline",
    "settings"
  ],
  "aperture-sharp": [
    "aperture",
    "dark",
    "images",
    "levels",
    "light",
    "settings",
    "sharp"
  ],
  apps: ["applications", "apps"],
  "apps-outline": ["applications", "apps", "outline"],
  "apps-sharp": ["applications", "apps", "sharp"],
  archive: ["archive", "email", "box", "catalog"],
  "archive-outline": ["archive", "email", "outline"],
  "archive-sharp": ["archive", "email", "sharp"],
  "arrow-back": ["arrow", "back", "chevron", "left", "navigation"],
  "arrow-back-circle": [
    "arrow",
    "back",
    "chevron",
    "circle",
    "left",
    "navigation"
  ],
  "arrow-back-circle-outline": [
    "arrow",
    "back",
    "chevron",
    "circle",
    "left",
    "navigation",
    "outline"
  ],
  "arrow-back-circle-sharp": [
    "arrow",
    "back",
    "chevron",
    "circle",
    "navigation",
    "sharp"
  ],
  "arrow-back-outline": ["arrow", "back", "left", "outline"],
  "arrow-back-sharp": [
    "arrow",
    "back",
    "chevron",
    "left",
    "navigation",
    "sharp"
  ],
  "arrow-down": ["arrow", "chevron", "down", "point", "direction"],
  "arrow-down-circle": ["arrow", "chevron", "circle", "down"],
  "arrow-down-circle-outline": [
    "arrow",
    "chevron",
    "circle",
    "down",
    "outline"
  ],
  "arrow-down-circle-sharp": ["arrow", "chevron", "circle", "down", "sharp"],
  "arrow-down-outline": ["arrow", "down", "outline"],
  "arrow-down-sharp": ["arrow", "chevron", "down", "sharp"],
  "arrow-forward": ["arrow", "chevron", "forward", "navigation", "right"],
  "arrow-forward-circle": [
    "arrow",
    "chevron",
    "circle",
    "forward",
    "navigation",
    "right"
  ],
  "arrow-forward-circle-outline": [
    "arrow",
    "chevron",
    "circle",
    "forward",
    "navigation",
    "outline",
    "right"
  ],
  "arrow-forward-circle-sharp": [
    "arrow",
    "chevron",
    "circle",
    "forward",
    "navigation",
    "right",
    "sharp"
  ],
  "arrow-forward-outline": ["arrow", "forward", "outline", "right"],
  "arrow-forward-sharp": [
    "arrow",
    "chevron",
    "forward",
    "navigation",
    "right",
    "sharp"
  ],
  "arrow-redo": ["arrow", "redo"],
  "arrow-redo-circle": ["arrow", "circle", "redo"],
  "arrow-redo-circle-outline": ["arrow", "circle", "outline", "redo"],
  "arrow-redo-circle-sharp": ["arrow", "circle", "redo", "sharp"],
  "arrow-redo-outline": ["arrow", "outline", "redo"],
  "arrow-redo-sharp": ["arrow", "redo", "sharp"],
  "arrow-undo": ["arrow", "undo"],
  "arrow-undo-circle": ["arrow", "circle", "undo"],
  "arrow-undo-circle-outline": ["arrow", "circle", "outline", "undo"],
  "arrow-undo-circle-sharp": ["arrow", "circle", "sharp", "undo"],
  "arrow-undo-outline": ["arrow", "outline", "undo"],
  "arrow-undo-sharp": ["arrow", "sharp", "undo"],
  "arrow-up": ["arrow", "chevron", "up", "point", "direction"],
  "arrow-up-circle": ["arrow", "chevron", "circle", "up"],
  "arrow-up-circle-outline": ["arrow", "chevron", "circle", "outline", "up"],
  "arrow-up-circle-sharp": ["arrow", "chevron", "circle", "sharp", "up"],
  "arrow-up-outline": ["arrow", "outline", "up"],
  "arrow-up-sharp": ["arrow", "chevron", "sharp", "up"],
  at: ["@", "at"],
  "at-circle": ["@", "at", "circle"],
  "at-circle-outline": ["@", "at", "circle", "outline"],
  "at-circle-sharp": ["@", "at", "circle", "sharp"],
  "at-outline": ["at", "outline"],
  "at-sharp": ["@", "at", "sharp"],
  attach: ["attach"],
  "attach-outline": ["attach", "outline"],
  "attach-sharp": ["attach", "sharp"],
  backspace: ["backspace"],
  "backspace-outline": ["backspace", "outline"],
  "backspace-sharp": ["backspace", "sharp"],
  bandage: ["bandage"],
  "bandage-outline": ["bandage", "outline"],
  "bandage-sharp": ["bandage", "sharp"],
  "bar-chart": ["bar", "chart"],
  "bar-chart-outline": ["bar", "chart", "outline"],
  "bar-chart-sharp": ["bar", "chart", "sharp"],
  barbell: ["barbell", "exercise", "lifting", "weight"],
  "barbell-outline": ["barbell", "exercise", "lifting", "outline", "weight"],
  "barbell-sharp": ["barbell", "exercise", "lifting", "sharp", "weight"],
  barcode: ["barcode", "camera", "reader"],
  "barcode-outline": ["barcode", "camera", "outline", "reader"],
  "barcode-sharp": ["barcode", "camera", "reader", "sharp"],
  baseball: ["baseball"],
  "baseball-outline": ["baseball", "outline"],
  "baseball-sharp": ["baseball", "sharp"],
  basket: ["basket"],
  "basket-outline": ["basket", "outline"],
  "basket-sharp": ["basket", "sharp"],
  basketball: ["basketball"],
  "basketball-outline": ["basketball", "outline"],
  "basketball-sharp": ["basketball", "sharp"],
  "battery-charging": ["battery", "charging"],
  "battery-charging-outline": ["battery", "charging", "outline"],
  "battery-charging-sharp": ["battery", "charging", "sharp"],
  "battery-dead": ["battery", "dead"],
  "battery-dead-outline": ["battery", "dead", "outline"],
  "battery-dead-sharp": ["battery", "dead", "sharp"],
  "battery-full": ["battery", "full"],
  "battery-full-outline": ["battery", "full", "outline"],
  "battery-full-sharp": ["battery", "full", "sharp"],
  "battery-half": ["battery", "half"],
  "battery-half-outline": ["battery", "half", "outline"],
  "battery-half-sharp": ["battery", "half", "sharp"],
  beaker: [
    "beaker",
    "flask",
    "mixture",
    "potion",
    "experiment",
    "labs",
    "experimental",
    "feature",
    "test",
    "science",
    "education",
    "study",
    "development",
    "testing"
  ],
  "beaker-outline": ["beaker", "flask", "mixture", "outline", "potion"],
  "beaker-sharp": ["beaker", "flask", "mixture", "potion", "sharp"],
  bed: ["bed", "hotel", "sleep"],
  "bed-outline": ["bed", "hotel", "outline", "sleep"],
  "bed-sharp": ["bed", "hotel", "sharp", "sleep"],
  beer: ["beer", "drink", "eat", "food"],
  "beer-outline": ["beer", "drink", "eat", "food", "outline"],
  "beer-sharp": ["beer", "drink", "eat", "food", "sharp"],
  bicycle: ["bicycle", "bike", "exercise"],
  "bicycle-outline": ["bicycle", "bike", "exercise", "outline"],
  "bicycle-sharp": ["bicycle", "bike", "exercise", "sharp"],
  bluetooth: ["bluetooth", "cloud", "connection"],
  "bluetooth-outline": ["bluetooth", "cloud", "connection", "outline"],
  "bluetooth-sharp": ["bluetooth", "cloud", "connection", "sharp"],
  boat: ["boat"],
  "boat-outline": ["boat", "outline"],
  "boat-sharp": ["boat", "sharp"],
  body: ["body"],
  "body-outline": ["body", "outline"],
  "body-sharp": ["body", "sharp"],
  bonfire: ["bonfire", "heat", "hot"],
  "bonfire-outline": ["bonfire", "heat", "hot", "outline"],
  "bonfire-sharp": ["bonfire", "heat", "hot", "sharp"],
  book: ["book", "read", "journal", "wiki", "readme"],
  "book-outline": ["book", "outline", "read"],
  "book-sharp": ["book", "read", "sharp"],
  bookmark: ["bookmark", "favorite", "save", "tag", "tab", "star"],
  "bookmark-outline": ["bookmark", "favorite", "outline", "save", "tag"],
  "bookmark-sharp": ["bookmark", "favorite", "save", "sharp", "tag"],
  bookmarks: ["bookmarks", "favorite"],
  "bookmarks-outline": ["bookmarks", "favorite", "outline"],
  "bookmarks-sharp": ["bookmarks", "favorite", "sharp"],
  briefcase: ["briefcase", "folder", "organize", "suitcase", "business"],
  "briefcase-outline": ["briefcase", "folder", "organize", "outline"],
  "briefcase-sharp": ["briefcase", "folder", "organize", "sharp"],
  browsers: ["browsers", "square"],
  "browsers-outline": ["browsers", "outline", "square"],
  "browsers-sharp": ["browsers", "sharp", "square"],
  brush: ["brush"],
  "brush-outline": ["brush", "outline"],
  "brush-sharp": ["brush", "sharp"],
  bug: ["bug", "develop", "error", "hacker", "program", "insect", "issue"],
  "bug-outline": ["bug", "develop", "error", "hacker", "outline", "program"],
  "bug-sharp": ["bug", "develop", "error", "hacker", "program", "sharp"],
  build: ["build"],
  "build-outline": ["build", "outline"],
  "build-sharp": ["build", "sharp"],
  bulb: ["bulb"],
  "bulb-outline": ["bulb", "outline"],
  "bulb-sharp": ["bulb", "sharp"],
  bus: ["bus"],
  "bus-outline": ["bus", "outline"],
  "bus-sharp": ["bus", "sharp"],
  business: ["business"],
  "business-outline": ["business", "outline"],
  "business-sharp": ["business", "sharp"],
  cafe: ["cafe", "coffee", "cup"],
  "cafe-outline": ["cafe", "coffee", "cup", "outline"],
  "cafe-sharp": ["cafe", "coffee", "cup", "sharp"],
  calculator: ["arithmetic", "calculator", "math"],
  "calculator-outline": ["arithmetic", "calculator", "math", "outline"],
  "calculator-sharp": ["arithmetic", "calculator", "math", "sharp"],
  calendar: [
    "calendar",
    "date",
    "month",
    "week",
    "time",
    "day",
    "year",
    "appointment"
  ],
  "calendar-outline": ["calendar", "date", "month", "outline", "week"],
  "calendar-sharp": ["calendar", "date", "month", "sharp", "week"],
  call: ["call", "telephone"],
  "call-outline": ["call", "outline", "telephone"],
  "call-sharp": ["call", "sharp", "telephone"],
  camera: ["camera", "image", "photo"],
  "camera-outline": ["camera", "image", "outline", "photo"],
  "camera-reverse": ["camera", "reverse"],
  "camera-reverse-outline": ["camera", "outline", "reverse"],
  "camera-reverse-sharp": ["camera", "reverse", "sharp"],
  "camera-sharp": ["camera", "image", "photo", "sharp"],
  car: ["car"],
  "car-outline": ["car", "outline"],
  "car-sharp": ["car", "sharp"],
  "car-sport": ["car", "sport"],
  "car-sport-outline": ["car", "outline", "sport"],
  "car-sport-sharp": ["car", "sharp", "sport"],
  card: [
    "$",
    "card",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "price",
    "shopping"
  ],
  "card-outline": [
    "$",
    "card",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "outline",
    "price",
    "shopping"
  ],
  "card-sharp": [
    "$",
    "card",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "price",
    "sharp",
    "shopping"
  ],
  "caret-back": ["back", "caret"],
  "caret-back-circle": ["back", "caret", "circle"],
  "caret-back-circle-outline": ["back", "caret", "circle", "outline"],
  "caret-back-circle-sharp": ["back", "caret", "circle", "left", "sharp"],
  "caret-back-outline": ["back", "caret", "left", "outline"],
  "caret-back-sharp": ["back", "caret", "left", "sharp"],
  "caret-down": ["caret", "down"],
  "caret-down-circle": ["caret", "circle", "down"],
  "caret-down-circle-outline": ["caret", "circle", "down", "outline"],
  "caret-down-circle-sharp": ["caret", "circle", "down", "sharp"],
  "caret-down-outline": ["caret", "down", "outline"],
  "caret-down-sharp": ["caret", "down", "sharp"],
  "caret-forward": ["caret", "forward", "right"],
  "caret-forward-circle": ["caret", "circle", "forward", "right"],
  "caret-forward-circle-outline": [
    "caret",
    "circle",
    "forward",
    "outline",
    "right"
  ],
  "caret-forward-circle-sharp": [
    "caret",
    "circle",
    "forward",
    "right",
    "sharp"
  ],
  "caret-forward-outline": ["caret", "forward", "outline", "right"],
  "caret-forward-sharp": ["caret", "forward", "right", "sharp"],
  "caret-up": ["caret", "up"],
  "caret-up-circle": ["caret", "circle", "up"],
  "caret-up-circle-outline": ["caret", "circle", "outline", "up"],
  "caret-up-circle-sharp": ["caret", "circle", "sharp", "up"],
  "caret-up-outline": ["caret", "outline", "up"],
  "caret-up-sharp": ["caret", "sharp", "up"],
  cart: ["cart"],
  "cart-outline": ["cart", "outline"],
  "cart-sharp": ["cart", "sharp"],
  cash: [
    "$",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "price",
    "shopping"
  ],
  "cash-outline": [
    "$",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "outline",
    "price",
    "shopping"
  ],
  "cash-sharp": [
    "$",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "price",
    "sharp",
    "shopping"
  ],
  cellular: ["cellular"],
  "cellular-outline": ["cellular", "outline"],
  "cellular-sharp": ["cellular", "sharp"],
  chatbox: ["chatbox"],
  "chatbox-ellipses": ["chatbox", "ellipses"],
  "chatbox-ellipses-outline": ["chatbox", "ellipses", "outline"],
  "chatbox-ellipses-sharp": ["chatbox", "ellipses", "sharp"],
  "chatbox-outline": ["chatbox", "outline"],
  "chatbox-sharp": ["chatbox", "sharp"],
  chatbubble: ["chatbubble"],
  "chatbubble-ellipses": ["chatbubble", "ellipses"],
  "chatbubble-ellipses-outline": ["chatbubble", "ellipses", "outline"],
  "chatbubble-ellipses-sharp": ["chatbubble", "ellipses", "sharp"],
  "chatbubble-outline": ["chatbubble", "outline"],
  "chatbubble-sharp": ["chatbubble", "sharp"],
  chatbubbles: ["chatbubbles", "talk"],
  "chatbubbles-outline": ["chatbubbles", "outline", "talk"],
  "chatbubbles-sharp": ["chatbubbles", "sharp", "talk"],
  checkbox: ["checkbox"],
  "checkbox-outline": ["checkbox", "outline"],
  "checkbox-sharp": ["checkbox", "sharp"],
  checkmark: ["checkmark", "circle"],
  "checkmark-circle": ["checkmark", "circle"],
  "checkmark-circle-outline": ["checkmark", "circle", "outline"],
  "checkmark-circle-sharp": ["checkmark", "circle", "sharp"],
  "checkmark-done": ["checkmark", "done"],
  "checkmark-done-circle": ["checkmark", "circle", "done"],
  "checkmark-done-circle-outline": ["checkmark", "circle", "done", "outline"],
  "checkmark-done-circle-sharp": ["checkmark", "circle", "done", "sharp"],
  "checkmark-done-outline": ["checkmark", "done", "outline"],
  "checkmark-done-sharp": ["checkmark", "done", "sharp"],
  "checkmark-outline": ["checkmark", "outline"],
  "checkmark-sharp": ["checkmark", "circle", "sharp"],
  "chevron-back": ["back", "chevron", "left"],
  "chevron-back-circle": ["back", "chevron", "circle", "left"],
  "chevron-back-circle-outline": [
    "back",
    "chevron",
    "circle",
    "left",
    "outline"
  ],
  "chevron-back-circle-sharp": ["back", "chevron", "circle", "left", "sharp"],
  "chevron-back-outline": ["back", "chevron", "left", "outline"],
  "chevron-back-sharp": ["back", "chevron", "left", "sharp"],
  "chevron-down": ["chevron", "down", "triangle", "arrow"],
  "chevron-down-circle": ["chevron", "circle", "down"],
  "chevron-down-circle-outline": ["chevron", "circle", "down", "outline"],
  "chevron-down-circle-sharp": ["chevron", "circle", "down", "sharp"],
  "chevron-down-outline": ["chevron", "down", "outline"],
  "chevron-down-sharp": ["chevron", "down", "sharp"],
  "chevron-forward": ["chevron", "forward", "right"],
  "chevron-forward-circle": ["chevron", "circle", "forward", "right"],
  "chevron-forward-circle-outline": [
    "chevron",
    "circle",
    "forward",
    "outline",
    "right"
  ],
  "chevron-forward-circle-sharp": [
    "chevron",
    "circle",
    "forward",
    "right",
    "sharp"
  ],
  "chevron-forward-outline": ["chevron", "forward", "outline", "right"],
  "chevron-forward-sharp": ["chevron", "forward", "right", "sharp"],
  "chevron-up": ["chevron", "up", "triangle", "arrow"],
  "chevron-up-circle": ["chevron", "circle", "up"],
  "chevron-up-circle-outline": ["chevron", "circle", "outline", "up"],
  "chevron-up-circle-sharp": ["chevron", "circle", "sharp", "up"],
  "chevron-up-outline": ["chevron", "outline", "up"],
  "chevron-up-sharp": ["chevron", "sharp", "up"],
  clipboard: ["clipboard", "write"],
  "clipboard-outline": ["clipboard", "outline", "write"],
  "clipboard-sharp": ["clipboard", "sharp", "write"],
  close: ["circle", "close", "delete", "remove"],
  "close-circle": ["circle", "close", "delete", "remove"],
  "close-circle-outline": ["circle", "close", "delete", "outline", "remove"],
  "close-circle-sharp": ["circle", "close", "delete", "remove", "sharp"],
  "close-outline": ["circle", "close", "delete", "outline", "remove"],
  "close-sharp": ["circle", "close", "delete", "remove", "sharp"],
  cloud: ["circle", "cloud", "storage", "weather", "whether"],
  "cloud-circle": ["circle", "cloud", "storage", "weather", "whether"],
  "cloud-circle-outline": [
    "circle",
    "cloud",
    "outline",
    "storage",
    "weather",
    "whether"
  ],
  "cloud-circle-sharp": [
    "circle",
    "cloud",
    "sharp",
    "storage",
    "weather",
    "whether"
  ],
  "cloud-done": ["cloud", "done"],
  "cloud-done-outline": ["cloud", "done", "outline"],
  "cloud-done-sharp": ["cloud", "done", "sharp"],
  "cloud-download": ["cloud", "download", "storage", "save", "install", "get"],
  "cloud-download-outline": ["cloud", "download", "outline", "storage"],
  "cloud-download-sharp": ["cloud", "download", "sharp", "storage"],
  "cloud-offline": ["cloud", "offline"],
  "cloud-offline-outline": ["cloud", "offline", "outline"],
  "cloud-offline-sharp": ["cloud", "offline", "sharp"],
  "cloud-outline": [
    "circle",
    "cloud",
    "outline",
    "storage",
    "weather",
    "whether"
  ],
  "cloud-sharp": ["circle", "cloud", "sharp", "storage", "weather", "whether"],
  "cloud-upload": ["cloud", "storage", "upload", "put", "export"],
  "cloud-upload-outline": ["cloud", "outline", "storage", "upload"],
  "cloud-upload-sharp": ["cloud", "sharp", "storage", "upload"],
  cloudy: ["cloudy", "overcast", "weather", "whether"],
  "cloudy-night": ["cloudy", "night", "overcast", "weather", "whether"],
  "cloudy-night-outline": [
    "cloudy",
    "night",
    "outline",
    "overcast",
    "weather",
    "whether"
  ],
  "cloudy-night-sharp": [
    "cloudy",
    "night",
    "overcast",
    "sharp",
    "weather",
    "whether"
  ],
  "cloudy-outline": ["cloudy", "outline", "overcast", "weather", "whether"],
  "cloudy-sharp": ["cloudy", "overcast", "sharp", "weather", "whether"],
  code: ["code", "develop", "hacker", "program", "brackets"],
  "code-download": ["code", "develop", "download", "hacker", "program"],
  "code-download-outline": [
    "code",
    "develop",
    "download",
    "hacker",
    "outline",
    "program"
  ],
  "code-download-sharp": [
    "code",
    "develop",
    "download",
    "hacker",
    "program",
    "sharp"
  ],
  "code-outline": ["code", "develop", "hacker", "outline", "program"],
  "code-sharp": ["code", "develop", "hacker", "program", "sharp"],
  "code-slash": ["code", "slash"],
  "code-slash-outline": ["code", "outline", "slash"],
  "code-slash-sharp": ["code", "sharp", "slash"],
  "code-working": ["code", "develop", "hacker", "program", "working"],
  "code-working-outline": [
    "code",
    "develop",
    "hacker",
    "outline",
    "program",
    "working"
  ],
  "code-working-sharp": [
    "code",
    "develop",
    "hacker",
    "program",
    "sharp",
    "working"
  ],
  cog: ["cog", "gear", "options", "settings"],
  "cog-outline": ["cog", "gear", "options", "outline", "settings"],
  "cog-sharp": ["cog", "gear", "options", "settings", "sharp"],
  "color-fill": ["color", "fill"],
  "color-fill-outline": ["color", "fill", "outline"],
  "color-fill-sharp": ["color", "fill", "sharp"],
  "color-filter": ["color", "filter"],
  "color-filter-outline": ["color", "filter", "outline"],
  "color-filter-sharp": ["color", "filter", "sharp"],
  "color-palette": ["color", "palette"],
  "color-palette-outline": ["color", "outline", "palette"],
  "color-palette-sharp": ["color", "palette", "sharp"],
  "color-wand": ["color", "wand"],
  "color-wand-outline": ["color", "outline", "wand"],
  "color-wand-sharp": ["color", "sharp", "wand"],
  compass: ["compass", "directions", "location", "navigation"],
  "compass-outline": [
    "compass",
    "directions",
    "location",
    "navigation",
    "outline"
  ],
  "compass-sharp": ["compass", "directions", "location", "navigation", "sharp"],
  construct: ["construct"],
  "construct-outline": ["construct", "outline"],
  "construct-sharp": ["construct", "sharp"],
  contract: ["contract"],
  "contract-outline": ["contract", "outline"],
  "contract-sharp": ["contract", "sharp"],
  contrast: ["contrast", "dark", "images", "levels", "light", "settings"],
  "contrast-outline": [
    "contrast",
    "dark",
    "images",
    "levels",
    "light",
    "outline",
    "settings"
  ],
  "contrast-sharp": [
    "contrast",
    "dark",
    "images",
    "levels",
    "light",
    "settings",
    "sharp"
  ],
  copy: ["copy", "duplicate", "paper"],
  "copy-outline": ["copy", "duplicate", "outline", "paper"],
  "copy-sharp": ["copy", "duplicate", "paper", "sharp"],
  create: ["create", "edit"],
  "create-outline": ["create", "edit", "outline"],
  "create-sharp": ["create", "edit", "sharp"],
  crop: ["crop"],
  "crop-outline": ["crop", "outline"],
  "crop-sharp": ["crop", "sharp"],
  cube: ["box", "container", "cube", "square"],
  "cube-outline": ["box", "container", "cube", "outline", "square"],
  "cube-sharp": ["box", "container", "cube", "sharp", "square"],
  cut: ["cut"],
  "cut-outline": ["cut", "outline"],
  "cut-sharp": ["cut", "sharp"],
  desktop: ["desktop"],
  "desktop-outline": ["desktop", "outline"],
  "desktop-sharp": ["desktop", "sharp"],
  disc: ["cd", "disc", "vinyl"],
  "disc-outline": ["cd", "disc", "outline", "vinyl"],
  "disc-sharp": ["cd", "disc", "sharp", "vinyl"],
  document: ["document", "file", "paper"],
  "document-attach": ["attach", "document"],
  "document-attach-outline": ["attach", "document", "outline"],
  "document-attach-sharp": ["attach", "document", "sharp"],
  "document-outline": ["document", "file", "outline", "paper"],
  "document-sharp": ["document", "file", "paper", "sharp"],
  "document-text": ["document", "text"],
  "document-text-outline": ["document", "outline", "text"],
  "document-text-sharp": ["document", "sharp", "text"],
  documents: ["documents"],
  "documents-outline": ["documents", "outline"],
  "documents-sharp": ["documents", "sharp"],
  download: ["download", "export"],
  "download-outline": ["download", "export", "outline"],
  "download-sharp": ["download", "export", "sharp"],
  duplicate: ["duplicate"],
  "duplicate-outline": ["duplicate", "outline"],
  "duplicate-sharp": ["duplicate", "sharp"],
  ear: ["ear"],
  "ear-outline": ["ear", "outline"],
  "ear-sharp": ["ear", "sharp"],
  earth: ["earth"],
  "earth-outline": ["earth", "outline"],
  "earth-sharp": ["earth", "sharp"],
  easel: ["easel"],
  "easel-outline": ["easel", "outline"],
  "easel-sharp": ["easel", "sharp"],
  egg: ["baby", "bird", "birth", "egg", "twitter"],
  "egg-outline": ["baby", "bird", "birth", "egg", "outline", "twitter"],
  "egg-sharp": ["baby", "bird", "birth", "egg", "sharp", "twitter"],
  ellipse: ["circle", "ellipse"],
  "ellipse-outline": ["circle", "ellipse", "outline"],
  "ellipse-sharp": ["circle", "ellipse", "sharp"],
  "ellipsis-horizontal": ["ellipsis", "horizontal"],
  "ellipsis-horizontal-circle": ["circle", "ellipsis", "horizontal"],
  "ellipsis-horizontal-circle-outline": [
    "circle",
    "ellipsis",
    "horizontal",
    "outline"
  ],
  "ellipsis-horizontal-circle-sharp": [
    "circle",
    "ellipsis",
    "horizontal",
    "sharp"
  ],
  "ellipsis-horizontal-outline": ["ellipsis", "horizontal", "outline"],
  "ellipsis-horizontal-sharp": ["ellipsis", "horizontal", "sharp"],
  "ellipsis-vertical": ["ellipsis", "vertical"],
  "ellipsis-vertical-circle": ["circle", "ellipsis", "vertical"],
  "ellipsis-vertical-circle-outline": [
    "circle",
    "ellipsis",
    "outline",
    "vertical"
  ],
  "ellipsis-vertical-circle-sharp": ["circle", "ellipsis", "sharp", "vertical"],
  "ellipsis-vertical-outline": ["ellipsis", "outline", "vertical"],
  "ellipsis-vertical-sharp": ["ellipsis", "sharp", "vertical"],
  enter: ["enter"],
  "enter-outline": ["enter", "outline"],
  "enter-sharp": ["enter", "sharp"],
  exit: ["exit"],
  "exit-outline": ["exit", "outline"],
  "exit-sharp": ["exit", "sharp"],
  expand: ["expand", "resize"],
  "expand-outline": ["expand", "outline"],
  "expand-sharp": ["expand", "resize", "sharp"],
  eye: ["exposed", "eye", "look", "see", "view", "watch"],
  "eye-off": ["eye", "off"],
  "eye-off-outline": ["eye", "off", "outline"],
  "eye-off-sharp": ["eye", "off", "sharp"],
  "eye-outline": ["exposed", "eye", "look", "outline", "see", "view"],
  "eye-sharp": ["exposed", "eye", "look", "see", "sharp", "view"],
  eyedrop: ["eyedrop"],
  "eyedrop-outline": ["eyedrop", "outline"],
  "eyedrop-sharp": ["eyedrop", "sharp"],
  "fast-food": ["fast", "food"],
  "fast-food-outline": ["fast", "food", "outline"],
  "fast-food-sharp": ["fast", "food", "sharp"],
  female: ["dudette", "female", "girl", "lady", "woman"],
  "female-outline": ["dudette", "female", "girl", "lady", "outline", "woman"],
  "female-sharp": ["dudette", "female", "girl", "lady", "sharp", "woman"],
  "file-tray": ["file", "tray"],
  "file-tray-full": ["file", "full", "tray"],
  "file-tray-full-outline": ["file", "full", "outline", "tray"],
  "file-tray-full-sharp": ["file", "full", "sharp", "tray"],
  "file-tray-outline": ["file", "outline", "tray"],
  "file-tray-sharp": ["file", "sharp", "tray"],
  "file-tray-stacked": ["file", "stacked", "tray"],
  "file-tray-stacked-outline": ["file", "outline", "stacked", "tray"],
  "file-tray-stacked-sharp": ["file", "sharp", "stacked", "tray"],
  film: ["film"],
  "film-outline": ["film", "outline"],
  "film-sharp": ["film", "sharp"],
  filter: ["filter"],
  "filter-outline": ["filter", "outline"],
  "filter-sharp": ["filter", "sharp"],
  "finger-print": ["finger", "print"],
  "finger-print-outline": ["finger", "outline", "print"],
  "finger-print-sharp": ["finger", "print", "sharp"],
  fitness: ["fitness"],
  "fitness-outline": ["fitness", "outline"],
  "fitness-sharp": ["fitness", "sharp"],
  flag: ["favorite", "flag", "marker"],
  "flag-outline": ["favorite", "flag", "marker", "outline"],
  "flag-sharp": ["favorite", "flag", "marker", "sharp"],
  flame: ["fire", "flame", "heat", "hot", "burn", "trending"],
  "flame-outline": ["fire", "flame", "heat", "hot", "outline"],
  "flame-sharp": ["fire", "flame", "heat", "hot", "sharp"],
  flash: ["flash", "lightning", "weather", "whether"],
  "flash-off": ["flash", "off"],
  "flash-off-outline": ["flash", "off", "outline"],
  "flash-off-sharp": ["flash", "off", "sharp"],
  "flash-outline": ["flash", "lightning", "outline", "weather", "whether"],
  "flash-sharp": ["flash", "lightning", "sharp", "weather", "whether"],
  flashlight: ["flashlight"],
  "flashlight-outline": ["flashlight", "outline"],
  "flashlight-sharp": ["flashlight", "sharp"],
  flask: ["bubbles", "flask", "mixture", "potion"],
  "flask-outline": ["bubbles", "flask", "mixture", "outline", "potion"],
  "flask-sharp": ["bubbles", "flask", "mixture", "potion", "sharp"],
  flower: ["flower"],
  "flower-outline": ["flower", "outline"],
  "flower-sharp": ["flower", "sharp"],
  folder: ["file", "folder"],
  "folder-open": ["folder", "open"],
  "folder-open-outline": ["folder", "open", "outline"],
  "folder-open-sharp": ["folder", "open", "sharp"],
  "folder-outline": ["file", "folder", "outline"],
  "folder-sharp": ["file", "folder", "sharp"],
  football: ["football", "soccer"],
  "football-outline": ["football", "outline", "soccer"],
  "football-sharp": ["football", "sharp", "soccer"],
  funnel: ["funnel", "sort"],
  "funnel-outline": ["funnel", "outline", "sort"],
  "funnel-sharp": ["funnel", "sharp", "sort"],
  "game-controller": ["controller", "game"],
  "game-controller-outline": ["controller", "game", "outline"],
  "game-controller-sharp": ["controller", "game", "sharp"],
  gift: ["gift", "package", "present", "skill", "craft", "freebie"],
  "gift-outline": ["gift", "outline"],
  "gift-sharp": ["gift", "sharp"],
  "git-branch": ["branch", "git", "fork", "duplicate"],
  "git-branch-outline": ["branch", "git", "outline"],
  "git-branch-sharp": ["branch", "git", "sharp"],
  "git-commit": ["commit", "git", "save"],
  "git-commit-outline": ["commit", "git", "outline"],
  "git-commit-sharp": ["commit", "git", "sharp"],
  "git-compare": ["compare", "git", "difference", "changes"],
  "git-compare-outline": ["compare", "git", "outline"],
  "git-compare-sharp": ["compare", "git", "sharp"],
  "git-merge": ["git", "merge", "join"],
  "git-merge-outline": ["git", "merge", "outline"],
  "git-merge-sharp": ["git", "merge", "sharp"],
  "git-network": ["git", "network"],
  "git-network-outline": ["git", "network", "outline"],
  "git-network-sharp": ["git", "network", "sharp"],
  "git-pull-request": ["git", "pull", "request", "review"],
  "git-pull-request-outline": ["git", "outline", "pull", "request"],
  "git-pull-request-sharp": ["git", "pull", "request", "sharp"],
  glasses: ["glasses", "look", "reading", "see", "steve"],
  "glasses-outline": ["glasses", "look", "outline", "reading", "see", "steve"],
  "glasses-sharp": ["glasses", "look", "reading", "see", "sharp", "steve"],
  globe: ["globe", "internet", "world", "earth", "planet"],
  "globe-outline": ["globe", "internet", "outline", "world"],
  "globe-sharp": ["globe", "internet", "sharp", "world"],
  golf: ["golf"],
  "golf-outline": ["golf", "outline"],
  "golf-sharp": ["golf", "sharp"],
  grid: ["grid", "menu"],
  "grid-outline": ["grid", "menu", "outline"],
  "grid-sharp": ["grid", "menu", "sharp"],
  hammer: ["hammer", "options", "settings", "tools"],
  "hammer-outline": ["hammer", "options", "outline", "settings", "tools"],
  "hammer-sharp": ["hammer", "options", "settings", "sharp", "tools"],
  "hand-left": ["hand", "left"],
  "hand-left-outline": ["hand", "left", "outline"],
  "hand-left-sharp": ["hand", "left", "sharp"],
  "hand-right": ["hand", "right"],
  "hand-right-outline": ["hand", "outline", "right"],
  "hand-right-sharp": ["hand", "right", "sharp"],
  happy: ["fun", "good", "happy", "like", "smile", "yes"],
  "happy-outline": ["fun", "good", "happy", "like", "outline", "smile", "yes"],
  "happy-sharp": ["fun", "good", "happy", "like", "sharp", "smile", "yes"],
  "hardware-chip": ["chip", "hardware"],
  "hardware-chip-outline": ["chip", "hardware", "outline"],
  "hardware-chip-sharp": ["chip", "hardware", "sharp"],
  headset: ["headset"],
  "headset-outline": ["headset", "outline"],
  "headset-sharp": ["headset", "sharp"],
  heart: ["heart", "love", "beat"],
  "heart-circle": ["circle", "heart", "love"],
  "heart-circle-outline": ["circle", "heart", "love", "outline"],
  "heart-circle-sharp": ["circle", "heart", "love", "sharp"],
  "heart-dislike": ["dislike", "heart", "love"],
  "heart-dislike-circle": ["circle", "dislike", "heart", "love"],
  "heart-dislike-circle-outline": [
    "circle",
    "dislike",
    "heart",
    "love",
    "outline"
  ],
  "heart-dislike-circle-sharp": ["circle", "dislike", "heart", "love", "sharp"],
  "heart-dislike-outline": ["dislike", "heart", "love", "outline"],
  "heart-dislike-sharp": ["dislike", "heart", "love", "sharp"],
  "heart-half": ["half", "heart", "love"],
  "heart-half-outline": ["half", "heart", "outline"],
  "heart-half-sharp": ["half", "heart", "love", "sharp"],
  "heart-outline": ["heart", "love", "outline", "beat"],
  "heart-sharp": ["heart", "love", "sharp"],
  help: ["?", "circle", "help", "information", "question"],
  "help-buoy": ["?", "buoy", "help", "question"],
  "help-buoy-outline": ["?", "buoy", "help", "outline", "question"],
  "help-buoy-sharp": ["?", "buoy", "help", "question", "sharp"],
  "help-circle": ["?", "circle", "help", "information", "question"],
  "help-circle-outline": [
    "?",
    "circle",
    "help",
    "information",
    "outline",
    "question"
  ],
  "help-circle-sharp": [
    "?",
    "circle",
    "help",
    "information",
    "question",
    "sharp"
  ],
  "help-outline": ["help", "outline"],
  "help-sharp": ["?", "circle", "help", "information", "question", "sharp"],
  home: ["home", "house", "welcome", "index", "building"],
  "home-outline": ["home", "house", "outline"],
  "home-sharp": ["home", "house", "sharp"],
  hourglass: ["hourglass", "time"],
  "hourglass-outline": ["hourglass", "outline", "time"],
  "hourglass-sharp": ["hourglass", "sharp", "time"],
  "ice-cream": ["cream", "ice"],
  "ice-cream-outline": ["cream", "ice", "outline"],
  "ice-cream-sharp": ["cream", "ice", "sharp"],
  image: ["camera", "image", "photo"],
  "image-outline": ["camera", "image", "outline", "photo"],
  "image-sharp": ["camera", "image", "photo", "sharp"],
  images: ["images", "photo"],
  "images-outline": ["images", "outline", "photo"],
  "images-sharp": ["images", "photo", "sharp"],
  infinite: ["forever", "infinite", "loop"],
  "infinite-outline": ["forever", "infinite", "loop", "outline"],
  "infinite-sharp": ["forever", "infinite", "loop", "sharp"],
  information: ["circle", "help", "information", "knowledge"],
  "information-circle": ["circle", "help", "information", "knowledge"],
  "information-circle-outline": [
    "circle",
    "help",
    "information",
    "knowledge",
    "outline"
  ],
  "information-circle-sharp": [
    "circle",
    "help",
    "information",
    "knowledge",
    "sharp"
  ],
  "information-outline": ["information", "outline"],
  "information-sharp": ["circle", "help", "information", "knowledge", "sharp"],
  journal: ["journal"],
  "journal-outline": ["journal", "outline"],
  "journal-sharp": ["journal", "sharp"],
  key: ["access", "key", "lock", "secure", "safe"],
  "key-outline": ["access", "key", "outline"],
  "key-sharp": ["access", "key", "sharp"],
  keypad: ["keypad", "type"],
  "keypad-outline": ["keypad", "outline", "type"],
  "keypad-sharp": ["keypad", "sharp", "type"],
  language: ["language"],
  "language-outline": ["language", "outline"],
  "language-sharp": ["language", "sharp"],
  laptop: ["apple", "laptop", "macbook", "osx"],
  "laptop-outline": ["apple", "laptop", "macbook", "osx", "outline"],
  "laptop-sharp": ["apple", "laptop", "macbook", "osx", "sharp"],
  layers: ["layers"],
  "layers-outline": ["layers", "outline"],
  "layers-sharp": ["layers", "sharp"],
  leaf: ["green", "leaf", "nature", "plant", "recycle"],
  "leaf-outline": ["green", "leaf", "nature", "outline", "plant", "recycle"],
  "leaf-sharp": ["green", "leaf", "nature", "plant", "recycle", "sharp"],
  library: ["library"],
  "library-outline": ["library", "outline"],
  "library-sharp": ["library", "sharp"],
  link: ["anchor", "attach", "chain", "href", "link", "connect", "hyperlink"],
  "link-outline": ["anchor", "attach", "chain", "href", "link", "outline"],
  "link-sharp": ["anchor", "attach", "chain", "href", "link", "sharp"],
  list: ["list"],
  "list-circle": ["circle", "list"],
  "list-circle-outline": ["circle", "list", "outline"],
  "list-circle-sharp": ["circle", "list", "sharp"],
  "list-outline": ["list", "outline"],
  "list-sharp": ["list", "sharp"],
  locate: ["gps", "locate", "maps", "navigate"],
  "locate-outline": ["gps", "locate", "maps", "navigate", "outline"],
  "locate-sharp": ["gps", "locate", "maps", "navigate", "sharp"],
  location: ["location", "here", "marker"],
  "location-outline": ["location", "outline"],
  "location-sharp": ["location", "sharp"],
  "lock-closed": ["closed", "lock"],
  "lock-closed-outline": ["closed", "lock", "outline"],
  "lock-closed-sharp": ["closed", "lock", "sharp"],
  "lock-open": ["lock", "open"],
  "lock-open-outline": ["lock", "open", "outline"],
  "lock-open-sharp": ["lock", "open", "sharp"],
  "log-in": ["login", "signin"],
  "log-in-outline": ["login", "outline", "signin"],
  "log-in-sharp": ["login", "sharp", "signin"],
  "log-out": ["logout", "signout"],
  "log-out-outline": ["logout", "outline", "signout"],
  "log-out-sharp": ["logout", "sharp", "signout"],
  "logo-amazon": ["amazon", "logo"],
  "logo-amplify": ["amplify", "logo"],
  "logo-android": ["android", "logo"],
  "logo-angular": ["angular", "logo"],
  "logo-apple": ["apple", "logo"],
  "logo-apple-appstore": ["apple", "appstore", "logo"],
  "logo-behance": ["behance", "logo"],
  "logo-bitbucket": ["bitbucket", "logo"],
  "logo-bitcoin": ["bitcoin", "logo"],
  "logo-buffer": ["buffer", "logo"],
  "logo-capacitor": ["capacitor", "logo"],
  "logo-chrome": ["chrome", "logo"],
  "logo-closed-captioning": ["captioning", "closed", "logo"],
  "logo-codepen": ["codepen", "logo"],
  "logo-css3": ["css3", "logo"],
  "logo-designernews": ["designernews", "logo"],
  "logo-docker": ["docker", "logo"],
  "logo-dribbble": ["dribbble", "logo"],
  "logo-dropbox": ["dropbox", "logo"],
  "logo-edge": ["edge", "logo"],
  "logo-electron": ["electron", "logo"],
  "logo-euro": ["euro", "logo"],
  "logo-facebook": ["facebook", "logo"],
  "logo-firebase": ["firebase", "logo"],
  "logo-firefox": ["firefox", "logo"],
  "logo-flickr": ["flickr", "logo"],
  "logo-foursquare": ["foursquare", "logo"],
  "logo-github": ["github", "logo", "brand"],
  "logo-gitlab": ["gitlab", "logo"],
  "logo-google": ["google", "logo"],
  "logo-google-playstore": ["google", "logo", "playstore"],
  "logo-hackernews": ["hackernews", "logo"],
  "logo-html5": ["html5", "logo"],
  "logo-instagram": ["instagram", "logo"],
  "logo-ionic": ["ionic", "logo"],
  "logo-ionitron": ["ionitron", "logo"],
  "logo-javascript": ["javascript", "logo"],
  "logo-laravel": ["laravel", "logo"],
  "logo-linkedin": ["linkedin", "logo"],
  "logo-markdown": ["logo", "markdown"],
  "logo-medium": ["logo", "medium"],
  "logo-no-smoking": ["logo", "no", "smoking"],
  "logo-nodejs": ["logo", "nodejs"],
  "logo-npm": ["logo", "npm"],
  "logo-octocat": ["logo", "octocat"],
  "logo-paypal": ["logo", "paypal"],
  "logo-pinterest": ["logo", "pinterest"],
  "logo-playstation": ["logo", "playstation"],
  "logo-pwa": ["logo", "pwa"],
  "logo-python": ["logo", "python"],
  "logo-react": ["logo", "react"],
  "logo-reddit": ["logo", "reddit"],
  "logo-rss": ["logo", "rss"],
  "logo-sass": ["logo", "sass"],
  "logo-skype": ["logo", "skype"],
  "logo-slack": ["logo", "slack"],
  "logo-snapchat": ["logo", "snapchat"],
  "logo-soundcloud": ["logo", "soundcloud"],
  "logo-stackoverflow": ["logo", "stackoverflow"],
  "logo-steam": ["logo", "steam"],
  "logo-stencil": ["logo", "stencil"],
  "logo-tiktok": ["logo", "tiktok"],
  "logo-tumblr": ["logo", "tumblr"],
  "logo-tux": ["logo", "tux"],
  "logo-twitch": ["logo", "twitch"],
  "logo-twitter": ["logo", "twitter"],
  "logo-usd": ["logo", "usd"],
  "logo-venmo": ["logo", "venmo"],
  "logo-vimeo": ["logo", "vimeo"],
  "logo-vk": ["logo", "vk"],
  "logo-vue": ["logo", "vue"],
  "logo-web-component": ["component", "logo", "web"],
  "logo-whatsapp": ["logo", "whatsapp"],
  "logo-windows": ["logo", "windows"],
  "logo-wordpress": ["logo", "wordpress"],
  "logo-xbox": ["logo", "xbox"],
  "logo-xing": ["logo", "xing"],
  "logo-yahoo": ["logo", "yahoo"],
  "logo-yen": ["logo", "yen"],
  "logo-youtube": ["logo", "youtube"],
  magnet: ["attraction", "magnet", "sticky"],
  "magnet-outline": ["attraction", "magnet", "outline", "sticky"],
  "magnet-sharp": ["attraction", "magnet", "sharp", "sticky"],
  mail: ["email", "mail", "unread"],
  "mail-open": ["mail", "open"],
  "mail-open-outline": ["mail", "open", "outline"],
  "mail-open-sharp": ["mail", "open", "sharp"],
  "mail-outline": ["email", "mail", "outline"],
  "mail-sharp": ["email", "mail", "sharp"],
  "mail-unread": ["mail", "unread"],
  "mail-unread-outline": ["mail", "outline", "unread"],
  "mail-unread-sharp": ["mail", "sharp", "unread"],
  male: ["boy", "dude", "guy", "male"],
  "male-female": ["female", "male"],
  "male-female-outline": ["female", "male", "outline"],
  "male-female-sharp": ["female", "male", "sharp"],
  "male-outline": ["male", "outline"],
  "male-sharp": ["boy", "dude", "guy", "male", "sharp"],
  man: ["boy", "dude", "guy", "male", "man"],
  "man-outline": ["boy", "dude", "guy", "male", "man", "outline"],
  "man-sharp": ["boy", "dude", "guy", "male", "man", "sharp"],
  map: ["gps", "map", "navigation", "pin"],
  "map-outline": ["gps", "map", "navigation", "outline", "pin"],
  "map-sharp": ["gps", "map", "navigation", "pin", "sharp"],
  medal: ["medal"],
  "medal-outline": ["medal", "outline"],
  "medal-sharp": ["medal", "sharp"],
  medical: ["medical"],
  "medical-outline": ["medical", "outline"],
  "medical-sharp": ["medical", "sharp"],
  medkit: ["case", "disease", "firstaid", "health", "medkit", "sick"],
  "medkit-outline": [
    "case",
    "disease",
    "firstaid",
    "health",
    "medkit",
    "outline",
    "sick"
  ],
  "medkit-sharp": [
    "case",
    "disease",
    "firstaid",
    "health",
    "medkit",
    "sharp",
    "sick"
  ],
  megaphone: ["megaphone", "bullhorn", "loud", "shout", "broadcast"],
  "megaphone-outline": ["megaphone", "outline"],
  "megaphone-sharp": ["megaphone", "sharp"],
  menu: ["menu"],
  "menu-outline": ["menu", "outline"],
  "menu-sharp": ["menu", "sharp"],
  mic: ["mic", "noise", "sound", "speaker", "talk"],
  "mic-circle": ["circle", "mic", "noise", "sound", "speaker", "talk"],
  "mic-circle-outline": [
    "circle",
    "mic",
    "noise",
    "outline",
    "sound",
    "speaker",
    "talk"
  ],
  "mic-circle-sharp": [
    "circle",
    "mic",
    "noise",
    "sharp",
    "sound",
    "speaker",
    "talk"
  ],
  "mic-off": ["mic", "noise", "off", "sound", "speaker", "talk"],
  "mic-off-circle": [
    "circle",
    "mic",
    "noise",
    "off",
    "sound",
    "speaker",
    "talk"
  ],
  "mic-off-circle-outline": [
    "circle",
    "mic",
    "noise",
    "off",
    "outline",
    "sound",
    "speaker",
    "talk"
  ],
  "mic-off-circle-sharp": [
    "circle",
    "mic",
    "noise",
    "off",
    "sharp",
    "sound",
    "speaker",
    "talk"
  ],
  "mic-off-outline": [
    "mic",
    "noise",
    "off",
    "outline",
    "sound",
    "speaker",
    "talk"
  ],
  "mic-off-sharp": ["mic", "noise", "off", "sharp", "sound", "speaker", "talk"],
  "mic-outline": ["mic", "noise", "outline", "sound", "speaker", "talk"],
  "mic-sharp": ["mic", "noise", "sharp", "sound", "speaker", "talk"],
  moon: ["dark", "moon", "night", "sky"],
  "moon-outline": ["dark", "moon", "night", "outline", "sky"],
  "moon-sharp": ["dark", "moon", "night", "sharp", "sky"],
  move: ["move"],
  "move-outline": ["move", "outline"],
  "move-sharp": ["move", "sharp"],
  "musical-note": ["listening", "musical", "noise", "note", "play", "sound"],
  "musical-note-outline": [
    "listening",
    "musical",
    "noise",
    "note",
    "outline",
    "play",
    "sound"
  ],
  "musical-note-sharp": [
    "listening",
    "musical",
    "noise",
    "note",
    "play",
    "sharp",
    "sound"
  ],
  "musical-notes": ["listening", "musical", "noise", "notes", "play", "sound"],
  "musical-notes-outline": [
    "listening",
    "musical",
    "noise",
    "notes",
    "outline",
    "play",
    "sound"
  ],
  "musical-notes-sharp": [
    "listening",
    "musical",
    "noise",
    "notes",
    "play",
    "sharp",
    "sound"
  ],
  navigate: ["gps", "location", "map", "navigate", "pin"],
  "navigate-circle": ["circle", "gps", "location", "map", "navigate", "pin"],
  "navigate-circle-outline": [
    "circle",
    "gps",
    "location",
    "map",
    "navigate",
    "outline",
    "pin"
  ],
  "navigate-circle-sharp": [
    "circle",
    "gps",
    "location",
    "map",
    "navigate",
    "pin",
    "sharp"
  ],
  "navigate-outline": ["gps", "location", "map", "navigate", "outline", "pin"],
  "navigate-sharp": ["gps", "location", "map", "navigate", "pin", "sharp"],
  newspaper: ["newspaper"],
  "newspaper-outline": ["newspaper", "outline"],
  "newspaper-sharp": ["newspaper", "sharp"],
  notifications: ["notifications"],
  "notifications-circle": ["circle", "notifications"],
  "notifications-circle-outline": ["circle", "notifications", "outline"],
  "notifications-circle-sharp": ["circle", "notifications", "sharp"],
  "notifications-off": ["notifications", "off"],
  "notifications-off-circle": ["circle", "notifications", "off"],
  "notifications-off-circle-outline": [
    "circle",
    "notifications",
    "off",
    "outline"
  ],
  "notifications-off-circle-sharp": ["circle", "notifications", "off", "sharp"],
  "notifications-off-outline": ["notifications", "off", "outline"],
  "notifications-off-sharp": ["notifications", "off", "sharp"],
  "notifications-outline": ["notifications", "outline"],
  "notifications-sharp": ["notifications", "sharp"],
  nuclear: ["danger", "hazard", "nuclear", "warning"],
  "nuclear-outline": ["danger", "hazard", "nuclear", "outline", "warning"],
  "nuclear-sharp": ["danger", "hazard", "nuclear", "sharp", "warning"],
  nutrition: ["nutrition"],
  "nutrition-outline": ["nutrition", "outline"],
  "nutrition-sharp": ["nutrition", "sharp"],
  open: ["open"],
  "open-outline": ["open", "outline"],
  "open-sharp": ["open", "sharp"],
  options: ["options"],
  "options-outline": ["options", "outline"],
  "options-sharp": ["options", "sharp"],
  "paper-plane": ["paper", "plane"],
  "paper-plane-outline": ["outline", "paper", "plane"],
  "paper-plane-sharp": ["paper", "plane", "sharp"],
  "partly-sunny": ["partly", "sunny"],
  "partly-sunny-outline": ["outline", "partly", "sunny"],
  "partly-sunny-sharp": ["partly", "sharp", "sunny"],
  pause: ["break", "freeze", "hold", "music", "pause"],
  "pause-circle": ["break", "circle", "freeze", "hold", "music", "pause"],
  "pause-circle-outline": [
    "break",
    "circle",
    "freeze",
    "hold",
    "music",
    "outline",
    "pause"
  ],
  "pause-circle-sharp": [
    "break",
    "circle",
    "freeze",
    "hold",
    "music",
    "pause",
    "sharp"
  ],
  "pause-outline": ["break", "freeze", "hold", "music", "outline", "pause"],
  "pause-sharp": ["break", "freeze", "hold", "music", "pause", "sharp"],
  paw: ["paw"],
  "paw-outline": ["outline", "paw"],
  "paw-sharp": ["paw", "sharp"],
  pencil: ["pencil", "edit", "change", "update", "write"],
  "pencil-outline": ["outline", "pencil"],
  "pencil-sharp": ["pencil", "sharp"],
  people: ["head", "human", "people", "person", "stalker", "users"],
  "people-circle": [
    "circle",
    "head",
    "human",
    "people",
    "person",
    "stalker",
    "users"
  ],
  "people-circle-outline": [
    "circle",
    "head",
    "human",
    "outline",
    "people",
    "person",
    "stalker",
    "users"
  ],
  "people-circle-sharp": [
    "circle",
    "head",
    "human",
    "people",
    "person",
    "sharp",
    "stalker",
    "users"
  ],
  "people-outline": [
    "head",
    "human",
    "outline",
    "people",
    "person",
    "stalker",
    "users"
  ],
  "people-sharp": [
    "head",
    "human",
    "people",
    "person",
    "sharp",
    "stalker",
    "users"
  ],
  person: [
    "head",
    "human",
    "person",
    "staff",
    "users",
    "people",
    "man",
    "woman"
  ],
  "person-add": [
    "add",
    "head",
    "human",
    "member",
    "new",
    "person",
    "staff",
    "users"
  ],
  "person-add-outline": [
    "add",
    "head",
    "human",
    "member",
    "new",
    "outline",
    "person",
    "staff",
    "users"
  ],
  "person-add-sharp": [
    "add",
    "head",
    "human",
    "member",
    "new",
    "person",
    "sharp",
    "staff",
    "users"
  ],
  "person-circle": ["circle", "head", "human", "person", "staff", "users"],
  "person-circle-outline": [
    "circle",
    "head",
    "human",
    "outline",
    "person",
    "staff",
    "users"
  ],
  "person-circle-sharp": [
    "circle",
    "head",
    "human",
    "person",
    "sharp",
    "staff",
    "users"
  ],
  "person-outline": ["head", "human", "outline", "person", "staff", "users"],
  "person-remove": ["person", "remove"],
  "person-remove-outline": ["outline", "person", "remove"],
  "person-remove-sharp": ["person", "remove", "sharp"],
  "person-sharp": ["head", "human", "person", "sharp", "staff", "users"],
  "phone-landscape": ["landscape", "phone"],
  "phone-landscape-outline": ["landscape", "outline", "phone"],
  "phone-landscape-sharp": ["landscape", "phone", "sharp"],
  "phone-portrait": ["phone", "portrait"],
  "phone-portrait-outline": ["outline", "phone", "portrait"],
  "phone-portrait-sharp": ["phone", "portrait", "sharp"],
  "pie-chart": ["chart", "pie"],
  "pie-chart-outline": ["chart", "outline", "pie"],
  "pie-chart-sharp": ["chart", "pie", "sharp"],
  pin: ["gps", "location", "navigation", "pin", "save", "star", "bookmark"],
  "pin-outline": ["gps", "location", "navigation", "outline", "pin"],
  "pin-sharp": ["gps", "location", "navigation", "pin", "sharp"],
  pint: ["pint"],
  "pint-outline": ["outline", "pint"],
  "pint-sharp": ["pint", "sharp"],
  pizza: ["drink", "eat", "food", "pizza"],
  "pizza-outline": ["drink", "eat", "food", "outline", "pizza"],
  "pizza-sharp": ["drink", "eat", "food", "pizza", "sharp"],
  planet: ["globe", "home", "nature", "planet", "space", "world"],
  "planet-outline": [
    "globe",
    "home",
    "nature",
    "outline",
    "planet",
    "space",
    "world"
  ],
  "planet-sharp": [
    "globe",
    "home",
    "nature",
    "planet",
    "sharp",
    "space",
    "world"
  ],
  play: [
    "arrow",
    "music",
    "play",
    "right",
    "watch",
    "start",
    "begin",
    "action"
  ],
  "play-back": ["back", "left", "play"],
  "play-back-circle": ["back", "circle", "left", "play"],
  "play-back-circle-outline": ["back", "circle", "left", "outline", "play"],
  "play-back-circle-sharp": ["back", "circle", "left", "play", "sharp"],
  "play-back-outline": ["back", "left", "outline", "play"],
  "play-back-sharp": ["back", "left", "play", "sharp"],
  "play-circle": ["arrow", "circle", "music", "play", "right", "watch"],
  "play-circle-outline": [
    "arrow",
    "circle",
    "music",
    "outline",
    "play",
    "right",
    "watch"
  ],
  "play-circle-sharp": [
    "arrow",
    "circle",
    "music",
    "play",
    "right",
    "sharp",
    "watch"
  ],
  "play-forward": ["forward", "play", "right"],
  "play-forward-circle": ["circle", "forward", "play", "right"],
  "play-forward-circle-outline": [
    "circle",
    "forward",
    "outline",
    "play",
    "right"
  ],
  "play-forward-circle-sharp": ["circle", "forward", "play", "right", "sharp"],
  "play-forward-outline": ["forward", "outline", "play", "right"],
  "play-forward-sharp": ["forward", "play", "right", "sharp"],
  "play-outline": ["arrow", "music", "outline", "play", "right", "watch"],
  "play-sharp": ["arrow", "music", "play", "right", "sharp", "watch"],
  "play-skip-back": ["back", "left", "play", "skip"],
  "play-skip-back-circle": ["back", "circle", "left", "play", "skip"],
  "play-skip-back-circle-outline": [
    "back",
    "circle",
    "left",
    "outline",
    "play",
    "skip"
  ],
  "play-skip-back-circle-sharp": [
    "back",
    "circle",
    "left",
    "play",
    "sharp",
    "skip"
  ],
  "play-skip-back-outline": ["back", "left", "outline", "play", "skip"],
  "play-skip-back-sharp": ["back", "left", "play", "sharp", "skip"],
  "play-skip-forward": ["forward", "play", "skip"],
  "play-skip-forward-circle": ["circle", "forward", "play", "right", "skip"],
  "play-skip-forward-circle-outline": [
    "circle",
    "forward",
    "outline",
    "play",
    "right",
    "skip"
  ],
  "play-skip-forward-circle-sharp": [
    "circle",
    "forward",
    "play",
    "right",
    "sharp",
    "skip"
  ],
  "play-skip-forward-outline": ["forward", "outline", "play", "right", "skip"],
  "play-skip-forward-sharp": ["forward", "play", "right", "sharp", "skip"],
  podium: ["award", "compete", "competition", "lose", "podium", "win"],
  "podium-outline": [
    "award",
    "compete",
    "competition",
    "lose",
    "outline",
    "podium",
    "win"
  ],
  "podium-sharp": [
    "award",
    "compete",
    "competition",
    "lose",
    "podium",
    "sharp",
    "win"
  ],
  power: ["off", "on", "power"],
  "power-outline": ["off", "on", "outline", "power"],
  "power-sharp": ["off", "on", "power", "sharp"],
  pricetag: ["$", "commerce", "items", "money", "pricetag", "shopping"],
  "pricetag-outline": [
    "$",
    "commerce",
    "items",
    "money",
    "outline",
    "pricetag",
    "shopping"
  ],
  "pricetag-sharp": [
    "$",
    "commerce",
    "items",
    "money",
    "pricetag",
    "sharp",
    "shopping"
  ],
  pricetags: ["$", "commerce", "items", "money", "pricetags", "shopping"],
  "pricetags-outline": [
    "$",
    "commerce",
    "items",
    "money",
    "outline",
    "pricetags",
    "shopping"
  ],
  "pricetags-sharp": [
    "$",
    "commerce",
    "items",
    "money",
    "pricetags",
    "sharp",
    "shopping"
  ],
  print: ["print"],
  "print-outline": ["outline", "print"],
  "print-sharp": ["print", "sharp"],
  pulse: ["hot", "live", "pulse", "rate", "graph", "trend", "line", "activity"],
  "pulse-outline": ["hot", "live", "outline", "pulse", "rate"],
  "pulse-sharp": ["hot", "live", "pulse", "rate", "sharp"],
  push: ["push"],
  "push-outline": ["outline", "push"],
  "push-sharp": ["push", "sharp"],
  "qr-code": ["code", "qr"],
  "qr-code-outline": ["code", "outline", "qr"],
  "qr-code-sharp": ["code", "qr", "sharp"],
  radio: ["music", "radio"],
  "radio-button-off": ["button", "off", "radio"],
  "radio-button-off-outline": ["button", "off", "outline", "radio"],
  "radio-button-off-sharp": ["button", "off", "radio", "sharp"],
  "radio-button-on": ["button", "on", "radio"],
  "radio-button-on-outline": ["button", "on", "outline", "radio"],
  "radio-button-on-sharp": ["button", "on", "radio", "sharp"],
  "radio-outline": ["music", "outline", "radio"],
  "radio-sharp": ["music", "radio", "sharp"],
  rainy: ["cloud", "rainy", "water", "weather", "whether"],
  "rainy-outline": ["cloud", "outline", "rainy", "water", "weather", "whether"],
  "rainy-sharp": ["cloud", "rainy", "sharp", "water", "weather", "whether"],
  reader: ["reader"],
  "reader-outline": ["outline", "reader"],
  "reader-sharp": ["reader", "sharp"],
  receipt: ["receipt"],
  "receipt-outline": ["outline", "receipt"],
  "receipt-sharp": ["receipt", "sharp"],
  recording: ["film", "recording", "tape", "voicemail"],
  "recording-outline": ["film", "outline", "recording", "tape", "voicemail"],
  "recording-sharp": ["film", "recording", "sharp", "tape", "voicemail"],
  refresh: ["circle", "refresh", "reload", "renew", "reset"],
  "refresh-circle": ["circle", "refresh", "reload", "renew", "reset"],
  "refresh-circle-outline": [
    "circle",
    "outline",
    "refresh",
    "reload",
    "renew",
    "reset"
  ],
  "refresh-circle-sharp": [
    "circle",
    "refresh",
    "reload",
    "renew",
    "reset",
    "sharp"
  ],
  "refresh-outline": ["outline", "refresh"],
  "refresh-sharp": ["circle", "refresh", "reload", "renew", "reset", "sharp"],
  reload: ["reload"],
  "reload-circle": ["circle", "reload"],
  "reload-circle-outline": ["circle", "outline", "reload"],
  "reload-circle-sharp": ["circle", "reload", "sharp"],
  "reload-outline": ["outline", "reload"],
  "reload-sharp": ["reload", "sharp"],
  remove: ["circle", "minus", "remove", "subtract"],
  "remove-circle": ["circle", "minus", "remove", "subtract"],
  "remove-circle-outline": ["circle", "minus", "outline", "remove", "subtract"],
  "remove-circle-sharp": ["circle", "minus", "remove", "sharp", "subtract"],
  "remove-outline": ["outline", "remove"],
  "remove-sharp": ["circle", "minus", "remove", "sharp", "subtract"],
  "reorder-four": ["four", "reorder"],
  "reorder-four-outline": ["four", "outline", "reorder"],
  "reorder-four-sharp": ["four", "reorder", "sharp"],
  "reorder-three": ["reorder", "three"],
  "reorder-three-outline": ["outline", "reorder", "three"],
  "reorder-three-sharp": ["reorder", "sharp", "three"],
  "reorder-two": ["reorder", "two"],
  "reorder-two-outline": ["outline", "reorder", "two"],
  "reorder-two-sharp": ["reorder", "sharp", "two"],
  repeat: ["repeat"],
  "repeat-outline": ["outline", "repeat"],
  "repeat-sharp": ["repeat", "sharp"],
  resize: ["resize"],
  "resize-outline": ["outline", "resize"],
  "resize-sharp": ["resize", "sharp"],
  restaurant: ["eat", "restaurant"],
  "restaurant-outline": ["eat", "outline", "restaurant"],
  "restaurant-sharp": ["eat", "restaurant", "sharp"],
  "return-down-back": ["back", "down", "left", "return"],
  "return-down-back-outline": ["back", "down", "left", "outline", "return"],
  "return-down-back-sharp": ["back", "down", "left", "return", "sharp"],
  "return-down-forward": ["down", "forward", "return", "right"],
  "return-down-forward-outline": [
    "down",
    "forward",
    "outline",
    "return",
    "right"
  ],
  "return-down-forward-sharp": ["down", "forward", "return", "right", "sharp"],
  "return-up-back": ["back", "left", "return", "up"],
  "return-up-back-outline": ["back", "left", "outline", "return", "up"],
  "return-up-back-sharp": ["back", "left", "return", "sharp", "up"],
  "return-up-forward": ["forward", "return", "right", "up"],
  "return-up-forward-outline": ["forward", "outline", "return", "right", "up"],
  "return-up-forward-sharp": ["forward", "return", "right", "sharp", "up"],
  ribbon: ["ribbon"],
  "ribbon-outline": ["outline", "ribbon"],
  "ribbon-sharp": ["ribbon", "sharp"],
  rocket: [
    "rocket",
    "staff",
    "stafftools",
    "blast",
    "off",
    "space",
    "launch",
    "ship"
  ],
  "rocket-outline": ["outline", "rocket"],
  "rocket-sharp": ["rocket", "sharp"],
  rose: ["flower", "rose"],
  "rose-outline": ["flower", "outline", "rose"],
  "rose-sharp": ["flower", "rose", "sharp"],
  sad: ["bad", "cry", "no", "sad"],
  "sad-outline": ["bad", "cry", "no", "outline", "sad"],
  "sad-sharp": ["bad", "cry", "no", "sad", "sharp"],
  save: ["save"],
  "save-outline": ["outline", "save"],
  "save-sharp": ["save", "sharp"],
  scan: ["scan"],
  "scan-circle": ["circle", "scan"],
  "scan-circle-outline": ["circle", "outline", "scan"],
  "scan-circle-sharp": ["circle", "scan", "sharp"],
  "scan-outline": ["outline", "scan"],
  "scan-sharp": ["scan", "sharp"],
  school: ["school"],
  "school-outline": ["outline", "school"],
  "school-sharp": ["school", "sharp"],
  search: ["glass", "magnifying", "search"],
  "search-circle": ["circle", "glass", "magnifying", "search"],
  "search-circle-outline": [
    "circle",
    "glass",
    "magnifying",
    "outline",
    "search"
  ],
  "search-circle-sharp": ["circle", "glass", "magnifying", "search", "sharp"],
  "search-outline": ["glass", "magnifying", "outline", "search"],
  "search-sharp": ["glass", "magnifying", "search", "sharp"],
  send: ["email", "paper", "send"],
  "send-outline": ["email", "outline", "paper", "send"],
  "send-sharp": ["email", "paper", "send", "sharp"],
  server: ["server", "computers", "racks", "ops"],
  "server-outline": ["outline", "server"],
  "server-sharp": ["server", "sharp"],
  settings: ["options", "settings", "sliders", "filters", "controls", "levels"],
  "settings-outline": ["options", "outline", "settings"],
  "settings-sharp": ["options", "settings", "sharp"],
  shapes: ["shapes"],
  "shapes-outline": ["outline", "shapes"],
  "shapes-sharp": ["shapes", "sharp"],
  share: ["share"],
  "share-outline": ["outline", "share"],
  "share-sharp": ["share", "sharp"],
  "share-social": ["share", "social"],
  "share-social-outline": ["outline", "share", "social"],
  "share-social-sharp": ["share", "sharp", "social"],
  shield: ["shield", "security", "protection"],
  "shield-checkmark": ["checkmark", "shield"],
  "shield-checkmark-outline": ["checkmark", "outline", "shield"],
  "shield-checkmark-sharp": ["checkmark", "sharp", "shield"],
  "shield-outline": ["outline", "shield"],
  "shield-sharp": ["sharp", "shield"],
  shirt: ["shirt"],
  "shirt-outline": ["outline", "shirt"],
  "shirt-sharp": ["sharp", "shirt"],
  shuffle: ["random", "shuffle"],
  "shuffle-outline": ["outline", "shuffle"],
  "shuffle-sharp": ["random", "sharp", "shuffle"],
  skull: ["skull"],
  "skull-outline": ["outline", "skull"],
  "skull-sharp": ["sharp", "skull"],
  snow: ["cold", "snow"],
  "snow-outline": ["cold", "outline", "snow"],
  "snow-sharp": ["cold", "sharp", "snow"],
  speedometer: ["drive", "level", "speed", "speedometer"],
  "speedometer-outline": ["drive", "level", "outline", "speed", "speedometer"],
  "speedometer-sharp": ["drive", "level", "sharp", "speed", "speedometer"],
  square: ["square"],
  "square-outline": ["outline", "square"],
  "square-sharp": ["sharp", "square"],
  star: ["favorite", "star", "save", "remember", "like"],
  "star-half": ["favorite", "half", "rate", "star"],
  "star-half-outline": ["half", "outline", "star"],
  "star-half-sharp": ["favorite", "half", "rate", "sharp", "star"],
  "star-outline": ["favorite", "outline", "star"],
  "star-sharp": ["favorite", "sharp", "star"],
  "stats-chart": ["chart", "stats"],
  "stats-chart-outline": ["chart", "outline", "stats"],
  "stats-chart-sharp": ["chart", "sharp", "stats"],
  stop: ["stop", "block", "spam", "report"],
  "stop-circle": ["circle", "stop"],
  "stop-circle-outline": ["circle", "outline", "stop"],
  "stop-circle-sharp": ["circle", "sharp", "stop"],
  "stop-outline": ["outline", "stop"],
  "stop-sharp": ["sharp", "stop"],
  stopwatch: ["stopwatch", "time"],
  "stopwatch-outline": ["outline", "stopwatch", "time"],
  "stopwatch-sharp": ["sharp", "stopwatch", "time"],
  subway: ["subway"],
  "subway-outline": ["outline", "subway"],
  "subway-sharp": ["sharp", "subway"],
  sunny: ["light", "sky", "sunny", "weather", "whether"],
  "sunny-outline": ["light", "outline", "sky", "sunny", "weather", "whether"],
  "sunny-sharp": ["light", "sharp", "sky", "sunny", "weather", "whether"],
  "swap-horizontal": ["horizontal", "swap"],
  "swap-horizontal-outline": ["horizontal", "outline", "swap"],
  "swap-horizontal-sharp": ["horizontal", "sharp", "swap"],
  "swap-vertical": ["swap", "vertical"],
  "swap-vertical-outline": ["outline", "swap", "vertical"],
  "swap-vertical-sharp": ["sharp", "swap", "vertical"],
  sync: ["sync", "cycle", "refresh", "loop"],
  "sync-circle": ["circle", "sync"],
  "sync-circle-outline": ["circle", "outline", "sync"],
  "sync-circle-sharp": ["circle", "sharp", "sync"],
  "sync-outline": ["outline", "sync"],
  "sync-sharp": ["sharp", "sync"],
  "tablet-landscape": ["landscape", "tablet"],
  "tablet-landscape-outline": ["landscape", "outline", "tablet"],
  "tablet-landscape-sharp": ["landscape", "sharp", "tablet"],
  "tablet-portrait": ["portrait", "tablet"],
  "tablet-portrait-outline": ["outline", "portrait", "tablet"],
  "tablet-portrait-sharp": ["portrait", "sharp", "tablet"],
  tennisball: ["tennisball"],
  "tennisball-outline": ["outline", "tennisball"],
  "tennisball-sharp": ["sharp", "tennisball"],
  terminal: ["terminal", "code", "ops", "shell"],
  "terminal-outline": ["outline", "terminal"],
  "terminal-sharp": ["sharp", "terminal"],
  text: ["text"],
  "text-outline": ["outline", "text"],
  "text-sharp": ["sharp", "text"],
  thermometer: ["cold", "heat", "hot", "mercury", "temperature", "thermometer"],
  "thermometer-outline": [
    "cold",
    "heat",
    "hot",
    "mercury",
    "outline",
    "temperature",
    "thermometer"
  ],
  "thermometer-sharp": [
    "cold",
    "heat",
    "hot",
    "mercury",
    "sharp",
    "temperature",
    "thermometer"
  ],
  "thumbs-down": ["down", "thumbs"],
  "thumbs-down-outline": ["down", "outline", "thumbs"],
  "thumbs-down-sharp": ["down", "sharp", "thumbs"],
  "thumbs-up": ["thumbs", "up"],
  "thumbs-up-outline": ["outline", "thumbs", "up"],
  "thumbs-up-sharp": ["sharp", "thumbs", "up"],
  thunderstorm: [
    "cloudy",
    "lightning",
    "overcast",
    "rain",
    "sky",
    "storm",
    "thunderstorm",
    "weather",
    "whether"
  ],
  "thunderstorm-outline": [
    "cloudy",
    "lightning",
    "outline",
    "overcast",
    "rain",
    "sky",
    "storm",
    "thunderstorm",
    "weather",
    "whether"
  ],
  "thunderstorm-sharp": [
    "cloudy",
    "lightning",
    "overcast",
    "rain",
    "sharp",
    "sky",
    "storm",
    "thunderstorm",
    "weather",
    "whether"
  ],
  time: ["clock", "hour", "minute", "second", "time", "watch"],
  "time-outline": [
    "clock",
    "hour",
    "minute",
    "outline",
    "second",
    "time",
    "watch"
  ],
  "time-sharp": ["clock", "hour", "minute", "second", "sharp", "time", "watch"],
  timer: ["clock", "timer"],
  "timer-outline": ["clock", "outline", "timer"],
  "timer-sharp": ["clock", "sharp", "timer"],
  today: ["today"],
  "today-outline": ["outline", "today"],
  "today-sharp": ["sharp", "today"],
  toggle: ["switch", "toggle"],
  "toggle-outline": ["outline", "switch", "toggle"],
  "toggle-sharp": ["sharp", "switch", "toggle"],
  "trail-sign": ["sign", "trail"],
  "trail-sign-outline": ["outline", "sign", "trail"],
  "trail-sign-sharp": ["sharp", "sign", "trail"],
  train: ["train"],
  "train-outline": ["outline", "train"],
  "train-sharp": ["sharp", "train"],
  transgender: ["transgender"],
  "transgender-outline": ["outline", "transgender"],
  "transgender-sharp": ["sharp", "transgender"],
  trash: ["close", "delete", "remove", "trash"],
  "trash-bin": ["bin", "trash"],
  "trash-bin-outline": ["bin", "outline", "trash"],
  "trash-bin-sharp": ["bin", "sharp", "trash"],
  "trash-outline": ["close", "delete", "outline", "remove", "trash"],
  "trash-sharp": ["close", "delete", "remove", "sharp", "trash"],
  "trending-down": ["down", "trending"],
  "trending-down-outline": ["down", "outline", "trending"],
  "trending-down-sharp": ["down", "sharp", "trending"],
  "trending-up": ["trending", "up"],
  "trending-up-outline": ["outline", "trending", "up"],
  "trending-up-sharp": ["sharp", "trending", "up"],
  triangle: ["triangle"],
  "triangle-outline": ["outline", "triangle"],
  "triangle-sharp": ["sharp", "triangle"],
  trophy: ["award", "compete", "competition", "lose", "trophy", "win"],
  "trophy-outline": [
    "award",
    "compete",
    "competition",
    "lose",
    "outline",
    "trophy",
    "win"
  ],
  "trophy-sharp": [
    "award",
    "compete",
    "competition",
    "lose",
    "sharp",
    "trophy",
    "win"
  ],
  tv: ["television", "tv"],
  "tv-outline": ["outline", "television", "tv"],
  "tv-sharp": ["sharp", "television", "tv"],
  umbrella: ["dry", "rain", "shelter", "umbrella", "wet"],
  "umbrella-outline": ["dry", "outline", "rain", "shelter", "umbrella", "wet"],
  "umbrella-sharp": ["dry", "rain", "sharp", "shelter", "umbrella", "wet"],
  videocam: ["camera", "film", "movie", "videocam"],
  "videocam-outline": ["camera", "film", "movie", "outline", "videocam"],
  "videocam-sharp": ["camera", "film", "movie", "sharp", "videocam"],
  "volume-high": ["high", "volume"],
  "volume-high-outline": ["high", "outline", "volume"],
  "volume-high-sharp": ["high", "sharp", "volume"],
  "volume-low": ["low", "volume"],
  "volume-low-outline": ["low", "outline", "volume"],
  "volume-low-sharp": ["low", "sharp", "volume"],
  "volume-medium": ["medium", "volume"],
  "volume-medium-outline": ["medium", "outline", "volume"],
  "volume-medium-sharp": ["medium", "sharp", "volume"],
  "volume-mute": ["mute", "sound", "volume"],
  "volume-mute-outline": ["mute", "outline", "sound", "volume"],
  "volume-mute-sharp": ["mute", "sharp", "sound", "volume"],
  "volume-off": ["off", "volume"],
  "volume-off-outline": ["off", "outline", "volume"],
  "volume-off-sharp": ["off", "sharp", "volume"],
  walk: ["walk"],
  "walk-outline": ["outline", "walk"],
  "walk-sharp": ["sharp", "walk"],
  wallet: ["cash", "money", "wallet"],
  "wallet-outline": ["cash", "money", "outline", "wallet"],
  "wallet-sharp": ["cash", "money", "sharp", "wallet"],
  warning: ["warning"],
  "warning-outline": ["outline", "warning"],
  "warning-sharp": ["sharp", "warning"],
  watch: ["watch", "wait", "hourglass", "time", "date"],
  "watch-outline": ["outline", "watch"],
  "watch-sharp": ["sharp", "watch"],
  water: ["water"],
  "water-outline": ["outline", "water"],
  "water-sharp": ["sharp", "water"],
  wifi: ["bars", "connection", "internet", "wifi"],
  "wifi-outline": ["bars", "connection", "internet", "outline", "wifi"],
  "wifi-sharp": ["bars", "connection", "internet", "sharp", "wifi"],
  wine: ["glass", "wine"],
  "wine-outline": ["glass", "outline", "wine"],
  "wine-sharp": ["glass", "sharp", "wine"],
  woman: ["dudette", "female", "girl", "lady", "woman"],
  "woman-outline": ["dudette", "female", "girl", "lady", "outline", "woman"],
  "woman-sharp": ["dudette", "female", "girl", "lady", "sharp", "woman"],
  "arrow-both": ["point", "direction", "left", "right"],
  "arrow-left": ["point", "direction"],
  "arrow-right": ["point", "direction"],
  bell: ["notification"],
  bold: ["markdown", "bold", "text"],
  broadcast: ["rss", "radio", "signal"],
  browser: ["window", "web"],
  check: ["mark", "yes", "confirm", "accept", "ok", "success"],
  checklist: ["todo", "tasks"],
  "chevron-left": ["triangle", "arrow"],
  "chevron-right": ["triangle", "arrow"],
  "circle-slash": ["no", "deny", "fail", "failure", "error", "bad"],
  "circuit-board": ["developer", "hardware", "electricity"],
  clippy: ["copy", "paste", "save", "capture", "clipboard"],
  clock: ["time", "hour", "minute", "second", "watch"],
  comment: ["speak", "bubble"],
  "comment-discussion": ["converse", "talk"],
  "credit-card": ["money", "billing", "payments", "transactions"],
  dash: ["hyphen", "range"],
  dashboard: ["speed", "dial"],
  database: ["disks", "data"],
  dependent: ["dependency", "dependent", "file"],
  "desktop-download": ["clone", "download"],
  "device-camera": ["photo", "picture", "image", "snapshot"],
  "device-camera-video": ["watch", "view", "media", "stream"],
  "device-desktop": ["computer", "monitor"],
  "device-mobile": ["phone", "iphone", "cellphone"],
  diff: ["difference", "changes", "compare"],
  "diff-added": ["new", "addition", "plus"],
  "diff-ignored": ["slash"],
  "diff-modified": ["dot", "changed", "updated"],
  "diff-removed": ["deleted", "subtracted", "dash"],
  "diff-renamed": ["moved", "arrow"],
  ellipsis: ["dot", "read", "more", "hidden", "expand"],
  "eye-closed": ["hidden", "invisible", "concealed", ""],
  file: ["file", "text", "words"],
  "file-binary": ["image", "video", "word", "powerpoint", "excel"],
  "file-code": [
    "text",
    "javascript",
    "html",
    "css",
    "php",
    "ruby",
    "coffeescript",
    "sass",
    "scss"
  ],
  "file-directory": ["folder"],
  "file-media": ["image", "video", "audio"],
  "file-pdf": ["adobe"],
  "file-submodule": ["folder"],
  "file-symlink-directory": ["folder", "subfolder", "link", "alias"],
  "file-symlink-file": ["link", "alias"],
  "file-zip": ["compress", "archive"],
  fold: ["unfold", "hide", "collapse"],
  "fold-down": ["unfold", "hide", "collapse", "down"],
  "fold-up": ["unfold", "hide", "collapse", "up"],
  gear: ["settings"],
  gist: ["gist", "github"],
  "gist-secret": ["gist", "secret", "private"],
  "github-action": ["board", "workflow", "action", "automation"],
  grabber: ["mover", "drap", "drop", "sort"],
  graph: ["trend", "stats", "statistics"],
  history: ["time", "past", "revert", "back"],
  "horizontal-rule": ["hr"],
  hubot: ["robot", "bot"],
  inbox: ["mail", "todo", "new", "messages"],
  infinity: ["unlimited", "infinite"],
  info: ["help"],
  "internal-repo": ["internal, repo, repository"],
  "issue-closed": ["done", "complete"],
  "issue-opened": ["new"],
  "issue-reopened": ["regression"],
  italic: ["font", "italic", "style"],
  jersey: ["team", "game", "basketball"],
  "kebab-horizontal": ["kebab", "dot", "menu", "more"],
  "kebab-vertical": ["kebab", "dot", "menu", "more"],
  keyboard: ["type", "keys", "write", "shortcuts"],
  law: ["legal", "bill"],
  "light-bulb": ["idea"],
  "line-arrow-down": ["arrow", "point", "direction", "down"],
  "line-arrow-left": ["arrow", "point", "direction", "left"],
  "line-arrow-right": ["arrow", "point", "direction", "right"],
  "line-arrow-up": ["arrow", "point", "direction", "up"],
  "link-external": ["out", "see", "more", "go", "to"],
  "list-ordered": ["numbers", "tasks", "todo", "items"],
  "list-unordered": ["bullet", "point", "tasks", "todo", "items"],
  lock: ["secure", "safe", "protected"],
  "logo-gist": ["brand", "github", "logo"],
  "mail-read": ["email", "open"],
  "mark-github": ["octocat", "brand", "github", "logo"],
  markdown: ["markup", "style"],
  mention: ["at", "ping"],
  milestone: ["marker"],
  mirror: ["reflect"],
  "mortar-board": ["education", "learn", "teach"],
  mute: ["quiet", "sound", "audio", "turn", "off"],
  "no-newline": ["return"],
  "north-star": ["star", "snowflake", "asterisk"],
  note: ["card", "paper", "ticket"],
  octoface: ["octocat", "brand"],
  organization: ["people", "group", "team"],
  package: ["box", "ship"],
  paintcan: ["style", "theme", "art", "color"],
  plug: ["hook", "webhook"],
  plus: ["add", "new", "more"],
  "plus-small": ["add", "new", "more", "small"],
  "primitive-dot": ["circle"],
  "primitive-dot-stroke": ["circle", "dot", "unread"],
  "primitive-square": ["box"],
  project: ["board", "kanban", "columns", "scrum"],
  question: ["help", "explain"],
  quote: ["quotation"],
  "radio-tower": ["broadcast"],
  reply: ["reply all", "back"],
  repo: ["book", "journal", "repository"],
  "repo-clone": ["book", "journal", "repository"],
  "repo-force-push": ["book", "journal", "put"],
  "repo-forked": ["book", "journal", "copy"],
  "repo-pull": ["book", "journal", "get"],
  "repo-push": ["book", "journal", "repository", "put"],
  "repo-template": ["book", "new", "add", "template"],
  "repo-template-private": ["book", "new", "template"],
  report: ["report", "abuse", "flag"],
  "request-changes": ["diff", "changes", "request"],
  rss: ["broadcast", "feed", "atom"],
  ruby: ["code", "language"],
  saved: ["saved", "bookmark"],
  "screen-full": ["fullscreen", "expand"],
  "screen-normal": ["fullscreen", "expand", "exit"],
  "shield-check": ["security", "shield", "protection", "check", "success"],
  "shield-lock": ["protect", "shield", "lock"],
  "shield-x": ["security", "shield", "protection", "fail"],
  "sign-in": ["door", "arrow", "direction", "enter", "log in"],
  "sign-out": ["door", "arrow", "direction", "leave", "log out"],
  skip: ["skip", "slash"],
  smiley: ["emoji", "smile", "mood", "emotion"],
  squirrel: ["ship", "shipit", "launch"],
  tag: ["release"],
  tasklist: ["todo"],
  telescope: ["science", "space", "look", "view", "explore"],
  "text-size": ["font", "size", "text"],
  "three-bars": ["hamburger", "menu", "dropdown"],
  thumbsdown: ["thumb", "thumbsdown", "rejected", "dislike"],
  thumbsup: ["thumb", "thumbsup", "prop", "ship", "like"],
  tools: ["screwdriver", "wrench", "settings"],
  trashcan: ["garbage", "rubbish", "recycle", "delete"],
  "triangle-down": ["arrow", "point", "direction"],
  "triangle-left": ["arrow", "point", "direction"],
  "triangle-right": ["arrow", "point", "direction"],
  "triangle-up": ["arrow", "point", "direction"],
  unfold: ["expand", "open", "reveal"],
  unmute: ["loud", "volume", "audio", "sound", "play"],
  unsaved: ["unsaved", "bookmark"],
  unverified: ["insecure", "untrusted", "signed"],
  verified: ["trusted", "secure", "trustworthy", "signed"],
  versions: ["history", "commits"],
  workflow: ["workflow", "actions"],
  "workflow-all": ["workflow", "actions"],
  x: ["remove", "close", "delete"],
  zap: ["electricity", "lightning", "props", "like", "star", "save"]
};
