module.exports = [
  ["add", "increase", "include", "invite", "plus", "positive"],
  ["airplane", "plane", "rocket", "aircraft", "jet", "ship", "cab", "ship"],
  ["alarm", "clock", "time", "watch"],
  ["albums", "boxes", "slides", "square"],
  [
    "alert",
    "alarm",
    "hint",
    "!",
    "attention",
    "exclamation",
    "notice",
    "warning",
    "triangle",
    "point"
  ],
  ["analytics", "data", "metrics", "track"],
  ["game", "software", "application"],
  ["archive", "zip", "rar", "winrar", "compress"],
  ["at", "@", "mail"],
  ["bandage", "plaster", "gauze"],
  ["barbell", "exercise", "lifting", "weight"],
  ["barcode", "qrcode", "reader"],
  [
    "beaker",
    "flask",
    "mixture",
    "potion",
    "experiment",
    "labs",
    "experimental",
    "feature",
    "test",
    "science",
    "education",
    "study",
    "development",
    "testing"
  ],
  ["bed", "hotel", "sleep"],
  ["beer", "drink", "eat", "food"],
  ["bicycle", "bike", "exercise"],
  ["bluetooth", "cloud", "connection"],
  ["boat", "canoe"],
  ["body", "frame"],
  ["bonfire", "heat", "hot", 'fire'],
  ["book", "read", "journal", "wiki", "readme", "learn"],
  ["bookmark", "favorite", "save", "tag", "tab", "star"],
  ["briefcase", "organize", "suitcase", "business"],
  ["browsers", "square"],
  ["bug", "develop", "error", "hacker", "program", "insect", "issue"],
  ["business", "trade", "work", "employment", "career"],
  ["cafe", "coffee", "cup"],
  ["calculator", "arithmetic", "math"],
  ["calendar", "date", "month", "week", "time", "day", "year", "appointment"],
  ["call", "telephone"],
  ["camera", "image", "photo"],
  ["car", "machine", "automobile", "ride", "truck"],
  [
    "card",
    "$",
    "cash",
    "credit",
    "debit",
    "dollars",
    "money",
    "price",
    "shopping"
  ],
  ["cash", "$", "credit", "debit", "dollars", "money", "price", "shopping"],
  ["chatbubbles", "talk"],
  ["checkmark", "circle"],
  ["clipboard", "write"],
  ["close", "circle", "delete", "remove"],
  ["cloud", "circle", "storage", "weather", "whether"],
  ["cloudy", "overcast", "weather", "whether"],
  ["code", "develop", "hacker", "program", "brackets"],
  ["cog", "gear", "options", "settings"],
  ["compass", "directions", "location", "navigation"],
  ["contrast", "dark", "images", "levels", "light", "settings"],
  ["copy", "duplicate", "paper"],
  ["create", "edit"],
  ["cube", "box", "container", "square"],
  ["desktop", "pc", "computer", "monitor"],
  ["disc", "cd", "vinyl"],
  ["document", "file", "paper"],
  ["documents"],
  ["download", "export"],
  ["duplicate"],
  ["ear", "hear"],
  ["earth", "globe", "planet"],
  ["egg", "baby", "bird", "birth", "twitter"],
  ["ellipse", "circle"],
  ["enter", "arrive", "login"],
  ["exit", "logout", "leave"],
  ["expand", "resize"],
  ["eye", "exposed", "look", "see", "view", "watch"],
  ["female", "dudette", "girl", "lady", "woman"],
  ["fitness", "health", "vigor"],
  ["flag", "favorite", "marker"],
  ["flame", "fire", "heat", "hot", "burn", "trending"],
  ["flash", "lightning", "weather", "whether"],
  ["flashlight"],
  ["flask", "bubbles", "mixture", "potion"],
  ["flower", "blossom"],
  ["folder", "file"],
  ["football", "soccer"],
  ["funnel", "sort"],
  ["gift", "package", "present", "skill", "craft", "freebie"],
  ["glasses", "look", "reading", "see", "steve"],
  ["globe", "internet", "world", "earth", "planet"],
  ["golf", "sport"],
  ["grid", "menu"],
  ["hammer", "options", "settings", "tools"],
  ["happy", "fun", "good", "like", "smile", "yes"],
  ["headset", "music"],
  ["heart", "love", "beat"],
  ["help", "?", "circle", "information", "question"],
  ["home", "house", "welcome", "index", "building"],
  ["hourglass", "time"],
  ["image", "camera", "photo"],
  ["images", "photo"],
  ["infinite", "forever", "loop"],
  ["information", "circle", "help", "knowledge"],
  ["journal", "newspaper", "paper"],
  ["key", "access", "lock", "secure", "safe"],
  ["keypad", "type"],
  ["language", "tongue", "vocalism"],
  ["laptop", "apple", "macbook", "osx"],
  ["leaf", "green", "nature", "plant", "recycle"],
  ["library", "bookstore"],
  ["link", "anchor", "attach", "chain", "href", "connect", "hyperlink"],
  ["list", "index", "catalog"],
  ["locate", "gps", "maps", "navigate"],
  ["location", "here", "marker"],
  ["magnet", "attraction", "sticky"],
  ["mail", "email", "unread"],
  ["male", "boy", "dude", "guy"],
  ["man", "boy", "dude", "guy", "male"],
  ["map", "gps", "navigation", "pin"],
  ["medical", "pharmacy", "doctor"],
  ["medkit", "case", "disease", "firstaid", "health", "sick"],
  ["megaphone", "bullhorn", "loud", "shout", "broadcast"],
  ["mic", "noise", "sound", "speaker", "talk"],
  ["moon", "dark", "night", "sky"],
  ["move", "action", "motion"],
  ["navigate", "gps", "location", "map", "pin"],
  ["notifications"],
  ["nuclear", "danger", "hazard", "warning"],
  ["pause", "break", "freeze", "hold", "music"],
  ["paw", "dog", "claw", "animal", "cat"],
  ["pencil", "edit", "change", "update", "write"],
  ["people", "head", "human", "person", "stalker", "users"],
  ["person", "head", "human", "staff", "users", "people", "man", "woman"],
  ["pin", "gps", "location", "navigation", "save", "star", "bookmark"],
  ["pizza", "drink", "eat", "food"],
  ["planet", "globe", "home", "nature", "space", "world"],
  ["play", "arrow", "music", "right", "watch", "start", "begin", "action"],
  ["podium", "award", "compete", "competition", "lose", "win"],
  ["power", "off", "on"],
  ["pricetag", "$", "commerce", "items", "money", "shopping"],
  ["pulse", "hot", "live", "rate", "graph", "trend", "line", "activity"],
  ["radio", "music"],
  ["rainy", "cloud", "water", "weather", "whether"],
  ["recording", "film", "tape", "voicemail"],
  ["refresh", "circle", "reload", "renew", "reset"],
  ["remove", "circle", "minus", "subtract"],
  ["restaurant", "eat"],
  ["rocket", "staff", "stafftools", "blast", "off", "space", "launch", "ship"],
  ["rose", "flower"],
  ["sad", "bad", "cry", "no"],
  ["search", "glass", "magnifying"],
  ["send", "email", "paper"],
  ["server", "computers", "racks", "ops"],
  ["settings", "options", "sliders", "filters", "controls", "levels"],
  ["shield", "security", "protection"],
  ["shuffle", "random"],
  ["snow", "cold"],
  ["speedometer", "drive", "level", "speed"],
    ["star", "favorite", "save", "remember", "like"],
  ["stop", "block", "spam", "report"],
  ["stopwatch", "time"],
  ["sunny", "light", "sky", "weather", "whether"],
  ["sync", "cycle", "refresh", "loop"],
  ["terminal", "code", "ops", "shell"],
  ["thermometer", "cold", "heat", "hot", "mercury", "temperature"],
  [
    "thunderstorm",
    "cloudy",
    "lightning",
    "overcast",
    "rain",
    "sky",
    "storm",
    "weather",
    "whether"
  ],
  ["time", "clock", "hour", "minute", "second", "watch"],
  ["timer", "clock"],
  ["toggle", "switch"],
  ["trash", "close", "delete", "remove"],
  ["trophy", "award", "compete", "competition", "lose", "win"],
  ["tv", "television"],
  ["umbrella", "dry", "rain", "shelter", "wet"],
  ["videocam", "camera", "film", "movie"],
  ["wallet", "cash", "money"],
  ["watch", "wait", "hourglass", "time", "date"],
  ["wifi", "bars", "connection", "internet"],
  ["wine", "glass"],
  ["woman", "dudette", "female", "girl", "lady"],
  ["bell", "notification"],
  ["bold", "markdown", "text"],
  ["broadcast", "rss", "radio", "signal"],
  ["browser", "window", "web"],
  ["check", "mark", "yes", "confirm", "accept", "ok", "success"],
  ["checklist", "todo", "tasks"],
  ["clippy", "copy", "paste", "save", "capture", "clipboard"],
  ["clock", "time", "hour", "minute", "second", "watch"],
  ["comment", "speak", "bubble"],
  ["dash", "hyphen", "range"],
  ["dashboard", "speed", "dial"],
  ["database", "disks", "data"],
  ["dependent", "dependency", "file"],
  ["diff", "difference", "changes", "compare"],
  ["ellipsis", "dot", "read", "more", "hidden", "expand"],
  ["file", "text", "words"],
  ["fold", "unfold", "hide", "collapse"],
  ["gear", "settings"],
  ["gist", "github"],
  ["grabber", "mover", "drap", "drop", "sort"],
  ["graph", "trend", "stats", "statistics"],
  ["history", "time", "past", "revert", "back"],
  ["hubot", "robot", "bot"],
  ["inbox", "mail", "todo", "new", "messages"],
  ["infinity", "unlimited", "infinite"],
  ["info", "help"],
  ["italic", "font", "style"],
  ["jersey", "team", "game", "basketball"],
  ["keyboard", "type", "keys", "write", "shortcuts"],
  ["law", "legal", "bill"],
  ["lock", "secure", "safe", "protected"],
  ["markdown", "markup", "style"],
  ["mention", "at", "ping"],
  ["milestone", "marker"],
  ["mirror", "reflect"],
  ["mute", "quiet", "sound", "audio", "turn", "off"],
  ["note", "card", "paper", "ticket"],
  ["octoface", "octocat", "brand"],
  ["organization", "people", "group", "team"],
  ["package", "box", "ship"],
  ["paintcan", "style", "theme", "art", "color"],
  ["plug", "hook", "webhook"],
  ["plus", "add", "new", "more"],
  ["project", "board", "kanban", "columns", "scrum"],
  ["question", "help", "explain"],
  ["quote", "quotation"],
  ["reply", "reply all", "back"],
  ["repo", "book", "journal", "repository"],
  ["report", "abuse", "flag"],
  ["rss", "broadcast", "feed", "atom"],
  ["ruby", "code", "language"],
  ["saved", "bookmark"],
  ["skip", "slash"],
  ["smiley", "emoji", "smile", "mood", "emotion"],
  ["squirrel", "ship", "shipit", "launch"],
  ["tag", "release"],
  ["tasklist", "todo"],
  ["telescope", "science", "space", "look", "view", "explore"],
  ["thumbsdown", "thumb", "rejected", "dislike"],
  ["thumbsup", "thumb", "prop", "ship", "like"],
  ["tools", "screwdriver", "wrench", "settings"],
  ["trashcan", "garbage", "rubbish", "recycle", "delete"],
  ["unfold", "expand", "open", "reveal"],
  ["unmute", "loud", "volume", "audio", "sound", "play"],
  ["unsaved", "bookmark"],
  ["unverified", "insecure", "untrusted", "signed"],
  ["verified", "trusted", "secure", "trustworthy", "signed"],
  ["versions", "history", "commits"],
  ["workflow", "actions"],
  ["x", "remove", "close", "delete"],
  ["zap", "electricity", "lightning", "props", "like", "star", "save"]
];
